//! The Kind 2 view of a project: one self-contained `.lus` file that Kind 2
//! parses and whose semantics match the simulator and the generated C.
//!
//! The plain Lustre projection (`ol_lustre_emit`) is a readable rendering of
//! the model; this view is what the prover sees. It differs where Kind 2's
//! Lustre and C disagree or where Kind 2 lacks a construct:
//!
//! * **Contracts** are imported in each node's header (`(*@contract import
//!   C(…) returns (…); *)`) and the root carries `--%MAIN;` in its body.
//! * **Clocks**: Kind 2 rejects clocked locals, so clocked nodes are
//!   rewritten onto the base clock with held-value semantics
//!   ([`ol_ir::declock`]).
//! * **Integer `/` and `%`** are Euclidean in Kind 2 but truncate in C;
//!   they become calls to `__ol_div` / `__ol_mod`, which truncate.
//! * **Casts**: real → integer truncates like C (`__ol_trunc`, Kind 2's
//!   `int` floors); integer → real is `real(x)`; a narrowing integer cast
//!   wraps like C (`__ol_wrap_uint8`, …).
//! * **Iterators** (`map`, `fold`) are unrolled over the static array length.
//! * **Bit operations** have no Kind 2 counterpart on unbounded integers;
//!   they are declared as imported (uninterpreted) functions.
//!
//! What the view abstracts is returned as [`Kind2Input::notes`], so reports
//! can say what a proof assumes.

use std::collections::{BTreeMap, BTreeSet};
use std::fmt::Write as _;

use ol_contract_ir::{parse_contracts, ContractDef};
use ol_ir::{BinOp, Equation, Expr, IterKind, Local, NodeDef, NodeKind, Port, Project, Type};
use ol_lustre_emit::{emit_declarations, emit_node_annotated, Annotations};
use ol_typecheck::ExprTyper;

/// The generated Kind 2 input.
#[derive(Debug, Clone)]
pub struct Kind2Input {
    pub text: String,
    /// What the proof assumes about the model, in plain words.
    pub notes: Vec<String>,
}

/// Identifiers Kind 2's Lustre front end reserves. A model using one cannot
/// be proved until it is renamed.
pub const RESERVED: &[&str] = &[
    "activate", "and", "any", "assert", "bool", "check", "condact", "const", "contract", "current",
    "default", "div", "else", "enum", "every", "exists", "false", "fby", "forall", "frame",
    "function", "if", "import", "imported", "initial", "int", "int8", "int16", "int32", "int64",
    "let", "lsh", "merge", "mod", "node", "not", "of", "or", "pre", "provided", "reachable", "real",
    "restart", "returns", "rsh", "struct", "subrange", "tel", "then", "true", "type", "uint8",
    "uint16", "uint32", "uint64", "var", "when", "xor",
];

/// Build the Kind 2 view of `project` (every node; slice first to prove one
/// operator). Errors name what blocks a faithful view.
pub fn emit(project: &Project) -> Result<Kind2Input, Vec<String>> {
    let reserved = reserved_names(project);
    if !reserved.is_empty() {
        return Err(reserved
            .into_iter()
            .map(|(name, what)| {
                format!("`{name}` ({what}) is a Kind 2 keyword — rename it to prove this model")
            })
            .collect());
    }

    let contracts: Vec<ContractDef> =
        project.packages.iter().flat_map(|p| parse_contracts(&p.contracts).0).collect();

    // C semantics first (typing needs the original, clocked program), then
    // clock elimination on the result.
    let typer = ExprTyper::new(project);
    let mut rw = Rewriter::new(&typer);
    let mut semantic = project.clone();
    for pkg in &mut semantic.packages {
        for node in &mut pkg.nodes {
            *node = rw.node(node);
        }
    }
    let contracts: Vec<ContractDef> = contracts.iter().map(|c| rw.contract(c)).collect();
    let uses_clocks = semantic.all_nodes().any(ol_ir::node_uses_clocks);
    let declocked = ol_ir::declock_project(&semantic)
        .map_err(|errs| errs.into_iter().map(|e| e.to_string()).collect::<Vec<_>>())?;

    let mut out = String::new();
    let _ = writeln!(out, "-- Generated by OpenLustre Studio for Kind 2.");
    let _ = writeln!(out, "-- project: {}", project.name);
    let notes = notes(project, &rw, uses_clocks);
    for n in &notes {
        let _ = writeln!(out, "-- note: {n}");
    }
    out.push('\n');

    for pkg in &declocked.packages {
        emit_declarations(pkg, &mut out);
    }
    rw.emit_helpers(&mut out);
    for c in &contracts {
        super::emit_modern_contract(c, &mut out);
        out.push('\n');
    }
    for pkg in &declocked.packages {
        for n in &pkg.nodes {
            let contract_import = n
                .contract
                .as_ref()
                .filter(|c| contracts.iter().any(|d| &d.name == *c))
                .map(|c| {
                    let names = |ps: &[Port]| ps.iter().map(|p| p.name.as_str()).collect::<Vec<_>>().join(", ");
                    format!("import {c}({}) returns ({});", names(&n.inputs), names(&n.outputs))
                });
            let ann = Annotations { contract_import, main: project.main.as_deref() == Some(n.name.as_str()) };
            emit_node_annotated(n, &ann, &mut out);
            out.push('\n');
        }
    }
    Ok(Kind2Input { text: out, notes })
}

fn notes(project: &Project, rw: &Rewriter, uses_clocks: bool) -> Vec<String> {
    let mut ints = false;
    let mut floats = false;
    let mut see = |t: &Type| {
        let mut t = t;
        while let Type::Array { elem, .. } = t {
            t = elem;
        }
        ints |= t.is_integer() || matches!(t, Type::Char);
        floats |= t.is_float();
    };
    for n in project.all_nodes() {
        for p in n.inputs.iter().chain(&n.outputs) {
            see(&p.ty);
        }
        for l in &n.locals {
            see(&l.ty);
        }
    }
    let mut notes = Vec::new();
    if ints {
        notes.push(
            "integers are proved as mathematical integers — the result holds for the generated C \
             as long as no arithmetic overflows (integer division and casts follow C)"
                .to_string(),
        );
    }
    if floats {
        notes.push("floating-point values are proved as exact reals — rounding is not modeled".to_string());
    }
    if uses_clocks {
        notes.push(
            "clocked equations are proved in their base-clock form (values hold between ticks), \
             the semantics the simulator and the generated C execute"
                .to_string(),
        );
    }
    if !rw.bit_ops.is_empty() {
        notes.push(
            "bit operations are uninterpreted: a property proved valid holds for any result, \
             but a counterexample through one may be spurious"
                .to_string(),
        );
    }
    notes
}

/// Every declared name that collides with a Kind 2 keyword.
fn reserved_names(project: &Project) -> Vec<(String, String)> {
    let reserved: BTreeSet<&str> = RESERVED.iter().copied().collect();
    let mut hits = Vec::new();
    let mut check = |name: &str, what: String| {
        if reserved.contains(name) {
            hits.push((name.to_string(), what));
        }
    };
    for pkg in &project.packages {
        for t in &pkg.types {
            check(t.name(), "a type".into());
            match &t.body {
                ol_ir::TypeBody::Enum(e) => {
                    for v in &e.variants {
                        check(v, format!("a value of `{}`", e.name));
                    }
                }
                ol_ir::TypeBody::Record { name, fields } => {
                    for f in fields {
                        check(&f.name, format!("a field of `{name}`"));
                    }
                }
                ol_ir::TypeBody::Alias { .. } => {}
            }
        }
        for c in &pkg.constants {
            check(&c.name, "a constant".into());
        }
        for n in &pkg.nodes {
            check(&n.name, "an operator".into());
            for p in n.inputs.iter().chain(&n.outputs) {
                check(&p.name, format!("a port of `{}`", n.name));
            }
            for l in &n.locals {
                check(&l.name, format!("a local of `{}`", n.name));
            }
        }
        for c in parse_contracts(&pkg.contracts).0 {
            check(&c.name, "a contract".into());
            for g in &c.ghost_vars {
                check(&g.name, format!("a variable of contract `{}`", c.name));
            }
            for m in &c.modes {
                check(&m.name, format!("a mode of contract `{}`", c.name));
            }
        }
    }
    hits
}

/// Rewrites C semantics Kind 2 lacks into helper calls; remembers which
/// helpers to emit.
struct Rewriter<'a> {
    typer: &'a ExprTyper,
    div: bool,
    trunc: bool,
    wraps: BTreeSet<&'static str>,
    /// Bit-operation pseudo-functions used, by name.
    bit_ops: BTreeSet<String>,
}

/// The hoisted operands of unrolled iterators, per node.
struct NodeCx<'n> {
    node: &'n NodeDef,
    env: BTreeMap<String, Type>,
    taken: BTreeSet<String>,
    extra_locals: Vec<Local>,
    extra_eqs: Vec<Equation>,
}

impl<'a> Rewriter<'a> {
    fn new(typer: &'a ExprTyper) -> Self {
        Rewriter { typer, div: false, trunc: false, wraps: BTreeSet::new(), bit_ops: BTreeSet::new() }
    }

    fn node(&mut self, node: &NodeDef) -> NodeDef {
        if node.kind == NodeKind::Imported {
            return node.clone();
        }
        let env = ExprTyper::env(node);
        let taken = env.keys().cloned().collect();
        let mut cx = NodeCx { node, env, taken, extra_locals: vec![], extra_eqs: vec![] };
        let mut out = node.clone();
        out.equations = node
            .equations
            .iter()
            .map(|eq| Equation { lhs: eq.lhs.clone(), rhs: self.expr(&eq.rhs, &mut cx) })
            .collect();
        out.locals.extend(cx.extra_locals);
        out.equations.extend(cx.extra_eqs);
        out
    }

    fn contract(&mut self, c: &ContractDef) -> ContractDef {
        // Type contract expressions against its ports and ghost variables.
        let pseudo = NodeDef {
            name: c.name.clone(),
            kind: NodeKind::Operator,
            inputs: c.inputs.clone(),
            outputs: c.outputs.clone(),
            locals: c.ghost_vars.iter().map(|g| Local { name: g.name.clone(), ty: g.ty.clone() }).collect(),
            equations: vec![],
            contract: None,
            diagram: Default::default(),
            probes: Vec::new(),
        };
        let env = ExprTyper::env(&pseudo);
        let taken = env.keys().cloned().collect();
        let mut cx = NodeCx { node: &pseudo, env, taken, extra_locals: vec![], extra_eqs: vec![] };
        let mut out = c.clone();
        for g in &mut out.ghost_vars {
            g.definition = self.expr(&g.definition, &mut cx);
        }
        for a in &mut out.assumptions {
            a.expr = self.expr(&a.expr, &mut cx);
        }
        for g in &mut out.guarantees {
            g.expr = self.expr(&g.expr, &mut cx);
        }
        for m in &mut out.modes {
            m.requires = m.requires.iter().map(|e| self.expr(e, &mut cx)).collect();
            m.ensures = m.ensures.iter().map(|e| self.expr(e, &mut cx)).collect();
        }
        // Hoisted iterator operands become ghost variables.
        for (l, eq) in cx.extra_locals.into_iter().zip(cx.extra_eqs) {
            out.ghost_vars.push(ol_contract_ir::GhostVar { name: l.name, ty: l.ty, definition: eq.rhs });
        }
        out
    }

    fn type_of(&self, e: &Expr, cx: &NodeCx) -> Option<Type> {
        self.typer.type_of(cx.node, &cx.env, e)
    }

    fn is_integer(&self, e: &Expr, cx: &NodeCx) -> bool {
        self.type_of(e, cx).is_some_and(|t| t.is_integer() || matches!(t, Type::Char))
    }

    fn expr(&mut self, e: &Expr, cx: &mut NodeCx) -> Expr {
        match e {
            Expr::Binary { op: op @ (BinOp::Div | BinOp::Mod), lhs, rhs } if self.is_integer(lhs, cx) => {
                self.div = true;
                let f = if *op == BinOp::Div { "__ol_div" } else { "__ol_mod" };
                Expr::call(f, vec![self.expr(lhs, cx), self.expr(rhs, cx)])
            }
            Expr::Binary { op, lhs, rhs } if bit_op(*op).is_some() => {
                let f = bit_op(*op).expect("bit op");
                self.bit_ops.insert(f.to_string());
                Expr::call(f, vec![self.expr(lhs, cx), self.expr(rhs, cx)])
            }
            Expr::Cast { to, arg } => {
                let from = self.type_of(arg, cx);
                let a = self.expr(arg, cx);
                let to = self.typer.resolve(to);
                match from {
                    Some(from) if is_int(&from) && to.is_float() => Expr::call("real", vec![a]),
                    // Out of range is undefined in C: no wrap to model.
                    Some(from) if from.is_float() && is_int(&to) => {
                        self.trunc = true;
                        Expr::call("__ol_trunc", vec![a])
                    }
                    Some(from) if is_int(&from) && is_int(&to) => self.wrap(&from, &to, a),
                    // float ↔ float (exact reals) or an untypeable operand.
                    _ => a,
                }
            }
            Expr::Iterate { kind, node, init, arrays } => {
                let len = arrays.first().and_then(|a| match self.type_of(a, cx) {
                    Some(Type::Array { len, .. }) => Some(len),
                    _ => None,
                });
                let arrays: Vec<Expr> = arrays.iter().map(|a| self.expr(a, cx)).collect();
                let init = init.as_ref().map(|i| self.expr(i, cx));
                let Some(len) = len else {
                    // Untypeable: leave it for Kind 2 to reject loudly.
                    return Expr::Iterate { kind: *kind, node: node.clone(), init: init.map(Box::new), arrays };
                };
                let arrays: Vec<Expr> = arrays.into_iter().map(|a| cx.hoist(a, self)).collect();
                let at = |a: &Expr, i: u32| Expr::Index { base: Box::new(a.clone()), index: Box::new(Expr::int_lit(i as i64)) };
                match kind {
                    IterKind::Map => Expr::Array {
                        items: (0..len)
                            .map(|i| Expr::call(node.clone(), arrays.iter().map(|a| at(a, i)).collect()))
                            .collect(),
                    },
                    IterKind::Fold => {
                        let mut acc = init.unwrap_or_else(|| Expr::int_lit(0));
                        for i in 0..len {
                            acc = Expr::call(node.clone(), vec![acc, at(&arrays[0], i)]);
                        }
                        acc
                    }
                }
            }
            Expr::Const { .. } | Expr::Var { .. } => e.clone(),
            Expr::Unary { op, arg } => Expr::Unary { op: *op, arg: Box::new(self.expr(arg, cx)) },
            Expr::Binary { op, lhs, rhs } => Expr::bin(*op, self.expr(lhs, cx), self.expr(rhs, cx)),
            Expr::IfThenElse { cond, then_branch, else_branch } => Expr::if_then_else(
                self.expr(cond, cx),
                self.expr(then_branch, cx),
                self.expr(else_branch, cx),
            ),
            Expr::Pre { arg } => Expr::pre(self.expr(arg, cx)),
            Expr::Arrow { init, body } => Expr::arrow(self.expr(init, cx), self.expr(body, cx)),
            Expr::Call { node, args } => {
                Expr::call(node.clone(), args.iter().map(|a| self.expr(a, cx)).collect())
            }
            Expr::Field { base, field } => Expr::Field { base: Box::new(self.expr(base, cx)), field: field.clone() },
            Expr::Index { base, index } => Expr::Index {
                base: Box::new(self.expr(base, cx)),
                index: Box::new(self.expr(index, cx)),
            },
            Expr::Tuple { items } => Expr::Tuple { items: items.iter().map(|i| self.expr(i, cx)).collect() },
            Expr::Array { items } => Expr::Array { items: items.iter().map(|i| self.expr(i, cx)).collect() },
            Expr::Struct { ty, fields } => Expr::Struct {
                ty: ty.clone(),
                fields: fields
                    .iter()
                    .map(|f| ol_ir::FieldInit { field: f.field.clone(), value: self.expr(&f.value, cx) })
                    .collect(),
            },
            Expr::When { arg, clock, on } => Expr::When { arg: Box::new(self.expr(arg, cx)), clock: clock.clone(), on: *on },
            Expr::Merge { clock, on_true, on_false } => Expr::Merge {
                clock: clock.clone(),
                on_true: Box::new(self.expr(on_true, cx)),
                on_false: Box::new(self.expr(on_false, cx)),
            },
        }
    }

    /// `e` converted from integer type `from` to integer type `to`, wrapping
    /// like C when `to` cannot hold every value of `from`.
    fn wrap(&mut self, from: &Type, to: &Type, e: Expr) -> Expr {
        let (Some(f), Some(t)) = (int_range(from), int_range(to)) else { return e };
        if t.0 <= f.0 && f.1 <= t.1 {
            return e;
        }
        let name = wrap_name(to);
        self.wraps.insert(name);
        Expr::call(name, vec![e])
    }

    fn emit_helpers(&self, out: &mut String) {
        if self.div {
            out.push_str(
                "-- C division: truncates toward zero (Kind 2's `div` is Euclidean).\n\
                 function __ol_div(a: int; b: int) returns (q: int);\n\
                 var m: int;\n\
                 let\n  m = (if a >= 0 then a else - a) div (if b >= 0 then b else - b);\n  \
                 q = if (a >= 0) = (b >= 0) then m else - m;\ntel\n\n\
                 -- C remainder: takes the sign of the dividend.\n\
                 function __ol_mod(a: int; b: int) returns (r: int);\n\
                 let\n  r = a - b * __ol_div(a, b);\ntel\n\n",
            );
        }
        if self.trunc {
            out.push_str(
                "-- C real-to-integer conversion: truncates (Kind 2's `int` floors).\n\
                 function __ol_trunc(x: real) returns (y: int);\n\
                 let\n  y = if x >= 0.0 then int(x) else - int(- x);\ntel\n\n",
            );
        }
        for name in &self.wraps {
            let bits: u32 = name.trim_start_matches("__ol_wrap_").trim_start_matches(['u', 'i', 'n', 't']).parse().unwrap_or(32);
            let m: u128 = 1u128 << bits;
            let body = if name.starts_with("__ol_wrap_u") {
                format!("x mod {m}")
            } else {
                let h = m / 2;
                format!("((x + {h}) mod {m}) - {h}")
            };
            let _ = write!(
                out,
                "-- C conversion to a narrower integer type: wraps modulo 2^{bits}.\n\
                 function {name}(x: int) returns (y: int);\nlet\n  y = {body};\ntel\n\n"
            );
        }
        for f in &self.bit_ops {
            let _ = write!(
                out,
                "-- Bit operation, uninterpreted for the prover.\n\
                 function imported {f}(a: int; b: int) returns (y: int);\n\n"
            );
        }
    }
}

impl NodeCx<'_> {
    /// Bind a non-variable array operand to a fresh local so unrolling
    /// indexes it instead of copying it (and any call inside it).
    fn hoist(&mut self, e: Expr, rw: &Rewriter) -> Expr {
        if matches!(e, Expr::Var { .. }) {
            return e;
        }
        let ty = match rw.typer.type_of(self.node, &self.env, &e) {
            Some(t) => t,
            None => return e,
        };
        let mut n = 0usize;
        let name = loop {
            let c = format!("__ol_arr{n}");
            if self.taken.insert(c.clone()) {
                break c;
            }
            n += 1;
        };
        self.env.insert(name.clone(), ty.clone());
        self.extra_locals.push(Local { name: name.clone(), ty });
        self.extra_eqs.push(Equation { lhs: vec![name.clone()], rhs: e });
        Expr::var(name)
    }
}

fn is_int(t: &Type) -> bool {
    t.is_integer() || matches!(t, Type::Char)
}

fn int_range(t: &Type) -> Option<(i128, i128)> {
    Some(match t {
        Type::Int8 => (i8::MIN as i128, i8::MAX as i128),
        Type::Int16 => (i16::MIN as i128, i16::MAX as i128),
        Type::Int32 => (i32::MIN as i128, i32::MAX as i128),
        Type::Int64 => (i64::MIN as i128, i64::MAX as i128),
        Type::Uint8 | Type::Char => (0, u8::MAX as i128),
        Type::Uint16 => (0, u16::MAX as i128),
        Type::Uint32 => (0, u32::MAX as i128),
        Type::Uint64 => (0, u64::MAX as i128),
        _ => return None,
    })
}

fn wrap_name(t: &Type) -> &'static str {
    match t {
        Type::Int8 => "__ol_wrap_int8",
        Type::Int16 => "__ol_wrap_int16",
        Type::Int32 => "__ol_wrap_int32",
        Type::Int64 => "__ol_wrap_int64",
        Type::Uint8 | Type::Char => "__ol_wrap_uint8",
        Type::Uint16 => "__ol_wrap_uint16",
        Type::Uint32 => "__ol_wrap_uint32",
        _ => "__ol_wrap_uint64",
    }
}

fn bit_op(op: BinOp) -> Option<&'static str> {
    Some(match op {
        BinOp::BitAnd => "bit_and",
        BinOp::BitOr => "bit_or",
        BinOp::BitXor => "bit_xor",
        BinOp::Shl => "shift_left",
        BinOp::Shr => "shift_right",
        _ => return None,
    })
}
