//! OpenLustre Studio: CoCoSpec contract emitter (Phase 4).
//!
//! Two output dialects are supported per the implementation plan:
//!
//! * `Target::Modern` — Kind 2 `con/noc` block contract syntax, attached to a
//!   node by name.
//! * `Target::Legacy` — block-comment contract syntax (`(*@contract ... @*)`)
//!   for older Kind 2 versions and SCADE-style toolchains.
//!
//! Both targets emit the same logical contract; the IR is the source of truth.

use std::fmt::Write as _;

use ol_contract_ir::{parse_contracts, ContractDef};
use ol_ir::{NodeDef, Project};
use ol_lustre_emit::format_expr;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Target {
    Modern,
    Legacy,
}

/// Emit a top-level `contract` block (modern) plus inline references on
/// every node that declares one. For the legacy target, contracts are emitted
/// as block comments before each node body.
pub fn emit_project(project: &Project, target: Target) -> String {
    let mut out = String::new();
    let _ = writeln!(
        out,
        "-- Generated by OpenLustre Studio (contracts; {target:?})."
    );
    let _ = writeln!(out, "-- project: {}", project.name);
    out.push('\n');

    for pkg in &project.packages {
        let (contracts, _) = parse_contracts(&pkg.contracts);

        match target {
            Target::Modern => {
                for c in &contracts {
                    emit_modern_contract(c, &mut out);
                    out.push('\n');
                }
                for n in &pkg.nodes {
                    if let Some(cname) = &n.contract {
                        if let Some(_c) = contracts.iter().find(|c| c.name == *cname) {
                            emit_node_with_contract_ref(n, cname, &mut out);
                            out.push('\n');
                        }
                    }
                }
            }
            Target::Legacy => {
                for n in &pkg.nodes {
                    if let Some(cname) = &n.contract {
                        if let Some(c) = contracts.iter().find(|c| c.name == *cname) {
                            emit_legacy_node_contract(n, c, &mut out);
                            out.push('\n');
                        }
                    }
                }
            }
        }
    }

    out
}

fn emit_modern_contract(c: &ContractDef, out: &mut String) {
    let inputs = c
        .inputs
        .iter()
        .map(|p| format!("{}: {}", p.name, p.ty.lustre_name()))
        .collect::<Vec<_>>()
        .join("; ");
    let outputs = c
        .outputs
        .iter()
        .map(|p| format!("{}: {}", p.name, p.ty.lustre_name()))
        .collect::<Vec<_>>()
        .join("; ");
    let _ = writeln!(out, "contract {}({inputs}) returns ({outputs});", c.name);
    let _ = writeln!(out, "let");
    for g in &c.ghost_vars {
        let _ = writeln!(
            out,
            "  var {}: {} = {};",
            g.name,
            g.ty.lustre_name(),
            format_expr(&g.definition)
        );
    }
    for a in &c.assumptions {
        let label = a
            .name
            .as_ref()
            .map(|n| format!("\"{n}\" "))
            .unwrap_or_default();
        let _ = writeln!(out, "  assume {label}{};", format_expr(&a.expr));
    }
    for g in &c.guarantees {
        let label = g
            .name
            .as_ref()
            .map(|n| format!("\"{n}\" "))
            .unwrap_or_default();
        let _ = writeln!(out, "  guarantee {label}{};", format_expr(&g.expr));
    }
    for m in &c.modes {
        let _ = writeln!(out, "  mode {} (", m.name);
        for r in &m.requires {
            let _ = writeln!(out, "    require {};", format_expr(r));
        }
        for e in &m.ensures {
            let _ = writeln!(out, "    ensure {};", format_expr(e));
        }
        let _ = writeln!(out, "  );");
    }
    let _ = writeln!(out, "tel");
}

fn emit_node_with_contract_ref(node: &NodeDef, contract_name: &str, out: &mut String) {
    let kind = if node.is_function() { "function" } else { "node" };
    let inputs = node
        .inputs
        .iter()
        .map(|p| format!("{}: {}", p.name, p.ty.lustre_name()))
        .collect::<Vec<_>>()
        .join("; ");
    let outputs = node
        .outputs
        .iter()
        .map(|p| format!("{}: {}", p.name, p.ty.lustre_name()))
        .collect::<Vec<_>>()
        .join("; ");
    let _ = writeln!(out, "{kind} {}({inputs}) returns ({outputs});", node.name);
    let input_args = node
        .inputs
        .iter()
        .map(|p| p.name.clone())
        .collect::<Vec<_>>()
        .join(", ");
    let output_args = node
        .outputs
        .iter()
        .map(|p| p.name.clone())
        .collect::<Vec<_>>()
        .join(", ");
    let _ = writeln!(
        out,
        "(*@contract import {contract_name}({input_args}) returns ({output_args}); @*)"
    );
    let _ = writeln!(out, "-- see node body in main .lus file");
}

fn emit_legacy_node_contract(node: &NodeDef, c: &ContractDef, out: &mut String) {
    let _ = writeln!(out, "(*@contract");
    for a in &c.assumptions {
        let _ = writeln!(out, "  assume {};", format_expr(&a.expr));
    }
    for g in &c.guarantees {
        let _ = writeln!(out, "  guarantee {};", format_expr(&g.expr));
    }
    for m in &c.modes {
        let _ = writeln!(out, "  mode {} (", m.name);
        for r in &m.requires {
            let _ = writeln!(out, "    require {};", format_expr(r));
        }
        for e in &m.ensures {
            let _ = writeln!(out, "    ensure {};", format_expr(e));
        }
        let _ = writeln!(out, "  );");
    }
    let _ = writeln!(out, "@*)");
    let _ = writeln!(out, "-- contract above applies to node `{}`", node.name);
}
