//! Imported C operator wrapper generation (Phase 5, plan Task 14).
//!
//! An [`ImportedOperator`] manifest names an external C `symbol`, its `header`,
//! and its `source`. This module bridges the gap between OpenLustre's calling
//! convention (`{Name}_Input*` / `{Name}_Output*` structs) and the raw C
//! function, so a model that calls an imported operator can be code-generated
//! and compiled end-to-end.
//!
//! ## Wrapper ABI
//!
//! The generated wrapper assumes the external symbol obeys this convention:
//!
//! * Every input port is a parameter, in declaration order. Scalars are passed
//!   by value; arrays decay to a `const ELEM*` pointer.
//! * If there is exactly one scalar output, it is the function's return value.
//! * Otherwise every output is a trailing pointer parameter, in declaration
//!   order.
//!
//! The expected prototype is emitted as a comment in the wrapper header so the
//! author of the external C can match it exactly.

use std::fmt::Write as _;

use ol_ir::Type;

use crate::manifest::{parse_type, ImportedOperator, ImportedPort};

#[derive(Debug, Clone)]
pub struct ImportedWrapper {
    /// Wrapper header: Input/Output/State structs + `{name}_step` prototype.
    pub header: String,
    /// Wrapper source: the `{name}_step` body calling the external symbol.
    pub source: String,
    /// Files the build must compile and link, and include dirs it needs.
    pub build: BuildPlan,
}

#[derive(Debug, Clone, PartialEq)]
pub struct BuildPlan {
    /// The external C source file named by the manifest (relative path).
    pub external_source: String,
    /// The external header named by the manifest (relative path).
    pub external_header: String,
    /// The wrapper source file this module generates (suggested file name).
    pub wrapper_source: String,
}

fn param_decl(port: &ImportedPort) -> String {
    match parse_type(&port.ty_str) {
        Type::Array { elem, .. } => format!("const {}* {}", elem.c_name(), port.name),
        other => format!("{} {}", other.c_name(), port.name),
    }
}

fn arg_expr(port: &ImportedPort) -> String {
    // Arrays and scalars are both read straight off the input struct; arrays
    // decay to a pointer at the call site.
    format!("in->{}", port.name)
}

/// True when the operator returns its single output by value (exactly one
/// scalar output).
fn returns_by_value(op: &ImportedOperator) -> bool {
    op.outputs.len() == 1
        && !matches!(parse_type(&op.outputs[0].ty_str), Type::Array { .. })
}

/// The C prototype the external symbol must provide, per the wrapper ABI.
pub fn expected_prototype(op: &ImportedOperator) -> String {
    let mut params: Vec<String> = op.inputs.iter().map(param_decl).collect();
    if returns_by_value(op) {
        let ret = parse_type(&op.outputs[0].ty_str).c_name();
        let plist = if params.is_empty() {
            "void".to_string()
        } else {
            params.join(", ")
        };
        format!("{ret} {}({plist});", op.symbol)
    } else {
        for out in &op.outputs {
            params.push(match parse_type(&out.ty_str) {
                Type::Array { elem, .. } => format!("{}* {}", elem.c_name(), out.name),
                other => format!("{}* {}", other.c_name(), out.name),
            });
        }
        let plist = if params.is_empty() {
            "void".to_string()
        } else {
            params.join(", ")
        };
        format!("void {}({plist});", op.symbol)
    }
}

fn emit_io_structs(op: &ImportedOperator, out: &mut String) {
    let name = &op.name;
    let _ = writeln!(out, "typedef struct {{");
    if op.inputs.is_empty() {
        let _ = writeln!(out, "  int8_t _unused;");
    }
    for p in &op.inputs {
        let _ = writeln!(out, "  {};", field_decl(p));
    }
    let _ = writeln!(out, "}} {name}_Input;");
    out.push('\n');

    let _ = writeln!(out, "typedef struct {{");
    if op.outputs.is_empty() {
        let _ = writeln!(out, "  int8_t _unused;");
    }
    for p in &op.outputs {
        let _ = writeln!(out, "  {};", field_decl(p));
    }
    let _ = writeln!(out, "}} {name}_Output;");
    out.push('\n');
}

fn field_decl(port: &ImportedPort) -> String {
    match parse_type(&port.ty_str) {
        Type::Array { elem, len } => format!("{} {}[{}]", elem.c_name(), port.name, len),
        other => format!("{} {}", other.c_name(), port.name),
    }
}

pub fn emit_wrapper(op: &ImportedOperator) -> ImportedWrapper {
    let name = &op.name;
    let mut header = String::new();
    let mut source = String::new();

    let guard = format!("OL_IMPORTED_{}_H", name.to_uppercase());
    let _ = writeln!(header, "/* Generated by OpenLustre Studio (imported operator wrapper). */");
    let _ = writeln!(header, "#ifndef {guard}");
    let _ = writeln!(header, "#define {guard}");
    let _ = writeln!(header, "#include <stdbool.h>");
    let _ = writeln!(header, "#include <stdint.h>");
    header.push('\n');
    emit_io_structs(op, &mut header);
    let _ = writeln!(header, "/* The external C symbol `{}` must match: */", op.symbol);
    let _ = writeln!(header, "/*   {} */", expected_prototype(op));
    let _ = writeln!(
        header,
        "void {name}_step(const {name}_Input* in, {name}_Output* out);"
    );
    let _ = writeln!(header, "#endif /* {guard} */");

    let wrapper_header = format!("{name}_wrapper.h");
    let _ = writeln!(source, "/* Generated by OpenLustre Studio (imported operator wrapper). */");
    let _ = writeln!(source, "#include \"{wrapper_header}\"");
    let _ = writeln!(source, "#include \"{}\"", op.header);
    source.push('\n');
    let _ = writeln!(
        source,
        "void {name}_step(const {name}_Input* in, {name}_Output* out) {{"
    );
    let args: Vec<String> = op.inputs.iter().map(arg_expr).collect();
    if returns_by_value(op) {
        let out_field = &op.outputs[0].name;
        let _ = writeln!(source, "  out->{out_field} = {}({});", op.symbol, args.join(", "));
    } else {
        let mut all_args = args;
        for o in &op.outputs {
            // Scalars take the address of the output field; arrays decay.
            match parse_type(&o.ty_str) {
                Type::Array { .. } => all_args.push(format!("out->{}", o.name)),
                _ => all_args.push(format!("&out->{}", o.name)),
            }
        }
        let _ = writeln!(source, "  {}({});", op.symbol, all_args.join(", "));
    }
    let _ = writeln!(source, "}}");

    ImportedWrapper {
        header,
        source,
        build: BuildPlan {
            external_source: op.source.clone(),
            external_header: op.header.clone(),
            wrapper_source: format!("{name}_wrapper.c"),
        },
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::manifest::{ImportedContract, ImportedProperties};

    fn crc16() -> ImportedOperator {
        ImportedOperator {
            name: "CRC16_CCITT".into(),
            kind: "imported_operator".into(),
            language: "c".into(),
            header: "crc16.h".into(),
            source: "crc16.c".into(),
            symbol: "crc16_ccitt".into(),
            inputs: vec![
                ImportedPort { name: "data".into(), ty_str: "uint8[32]".into() },
                ImportedPort { name: "length".into(), ty_str: "uint32".into() },
            ],
            outputs: vec![ImportedPort { name: "crc".into(), ty_str: "uint16".into() }],
            contract: ImportedContract {
                properties: ImportedProperties {
                    pure: true,
                    no_dynamic_memory: true,
                    ..Default::default()
                },
                ..Default::default()
            },
        }
    }

    #[test]
    fn single_scalar_output_returns_by_value() {
        let op = crc16();
        assert_eq!(
            expected_prototype(&op),
            "uint16_t crc16_ccitt(const uint8_t* data, uint32_t length);"
        );
        let w = emit_wrapper(&op);
        assert!(w.source.contains("out->crc = crc16_ccitt(in->data, in->length);"));
        assert!(w.header.contains("} CRC16_CCITT_Input;"));
        assert!(w.header.contains("uint8_t data[32];"));
        assert!(w.source.contains("#include \"crc16.h\""));
        assert_eq!(w.build.external_source, "crc16.c");
    }

    #[test]
    fn multi_output_uses_pointer_params() {
        let mut op = crc16();
        op.outputs.push(ImportedPort { name: "ok".into(), ty_str: "bool".into() });
        op.symbol = "crc16_ex".into();
        assert_eq!(
            expected_prototype(&op),
            "void crc16_ex(const uint8_t* data, uint32_t length, uint16_t* crc, bool* ok);"
        );
        let w = emit_wrapper(&op);
        assert!(w
            .source
            .contains("crc16_ex(in->data, in->length, &out->crc, &out->ok);"));
    }
}
