//! OpenLustre Studio: Directional C-Lite emitter (Phase 5).
//!
//! Rules (from the implementation plan, Phase 5):
//! * No malloc/free, no recursion, no function pointers, no pointer arithmetic.
//! * No hidden globals, no implicit casts, no dynamic arrays.
//! * Fixed-width integer types only.
//! * Explicit state structs; explicit init/step entry points.
//! * Explicit input/output structs.
//!
//! Contracts produce *monitors* in a separate translation unit so production
//! C-Lite is not polluted with proof-only logic.

pub mod manifest;
pub mod monitor;

use std::collections::BTreeSet;
use std::fmt::Write as _;

use ol_ir::{BinOp, Equation, Expr, Literal, NodeDef, NodeKind, Project, Type, UnaryOp};

pub use manifest::{load_manifest_dir, ImportedOperator};

#[derive(Debug, Clone)]
pub struct EmittedClite {
    pub header: String,
    pub source: String,
}

pub fn emit_project(project: &Project) -> EmittedClite {
    let mut header = String::new();
    let mut source = String::new();

    let _ = writeln!(header, "/* Generated by OpenLustre Studio. */");
    let _ = writeln!(header, "#ifndef OL_GENERATED_H");
    let _ = writeln!(header, "#define OL_GENERATED_H");
    let _ = writeln!(header, "#include <stdbool.h>");
    let _ = writeln!(header, "#include <stdint.h>");
    let _ = writeln!(header, "#include <string.h>");
    header.push('\n');

    let _ = writeln!(source, "/* Generated by OpenLustre Studio. */");
    let _ = writeln!(source, "#include \"openlustre_generated.h\"");
    source.push('\n');

    for pkg in &project.packages {
        for node in &pkg.nodes {
            emit_node_header(node, &mut header);
            emit_node_source(node, &mut source);
        }
    }

    let _ = writeln!(header, "#endif /* OL_GENERATED_H */");
    EmittedClite { header, source }
}

fn emit_node_header(node: &NodeDef, out: &mut String) {
    let prefix = &node.name;
    let _ = writeln!(out, "/* --- {prefix} --- */");

    let _ = writeln!(out, "typedef struct {{");
    for p in &node.inputs {
        let _ = writeln!(out, "  {} {};", type_decl(&p.ty, &p.name), p.name);
    }
    if node.inputs.is_empty() {
        let _ = writeln!(out, "  int8_t _unused;");
    }
    let _ = writeln!(out, "}} {prefix}_Input;");
    out.push('\n');

    let _ = writeln!(out, "typedef struct {{");
    for p in &node.outputs {
        let _ = writeln!(out, "  {} {};", type_decl(&p.ty, &p.name), p.name);
    }
    if node.outputs.is_empty() {
        let _ = writeln!(out, "  int8_t _unused;");
    }
    let _ = writeln!(out, "}} {prefix}_Output;");
    out.push('\n');

    let state_fields = node_state_fields(node);
    let _ = writeln!(out, "typedef struct {{");
    let _ = writeln!(out, "  bool initialized;");
    for (name, ty) in &state_fields {
        let _ = writeln!(out, "  {} {name};", type_decl(ty, name));
    }
    let _ = writeln!(out, "}} {prefix}_State;");
    out.push('\n');

    if node.kind == NodeKind::Function {
        let _ = writeln!(out, "void {prefix}_step(const {prefix}_Input* in, {prefix}_Output* out);");
    } else {
        let _ = writeln!(out, "void {prefix}_init({prefix}_State* self);");
        let _ = writeln!(
            out,
            "void {prefix}_step({prefix}_State* self, const {prefix}_Input* in, {prefix}_Output* out);"
        );
    }
    if node.is_imported() {
        let _ = writeln!(out, "/* imported: implementation provided by external C. */");
    }
    out.push('\n');
}

fn emit_node_source(node: &NodeDef, out: &mut String) {
    if node.is_imported() {
        let _ = writeln!(
            out,
            "/* {0}_step is provided by the imported manifest for {0}. */",
            node.name
        );
        out.push('\n');
        return;
    }

    let prefix = &node.name;
    let state_fields = node_state_fields(node);

    if node.kind != NodeKind::Function {
        let _ = writeln!(out, "void {prefix}_init({prefix}_State* self) {{");
        let _ = writeln!(out, "  memset(self, 0, sizeof(*self));");
        let _ = writeln!(out, "  self->initialized = false;");
        let _ = writeln!(out, "}}");
        out.push('\n');
    }

    let sig = if node.kind == NodeKind::Function {
        format!("void {prefix}_step(const {prefix}_Input* in, {prefix}_Output* out)")
    } else {
        format!(
            "void {prefix}_step({prefix}_State* self, const {prefix}_Input* in, {prefix}_Output* out)"
        )
    };
    let _ = writeln!(out, "{sig} {{");

    for l in &node.locals {
        let _ = writeln!(out, "  {} {} = ({}) 0;", type_decl(&l.ty, &l.name), l.name, l.ty.c_name());
    }

    let scope = Scope {
        inputs: node.inputs.iter().map(|p| p.name.clone()).collect(),
        outputs: node.outputs.iter().map(|p| p.name.clone()).collect(),
        locals: node.locals.iter().map(|l| l.name.clone()).collect(),
        is_stateful: node.kind != NodeKind::Function,
    };

    for eq in &node.equations {
        emit_equation_body(eq, &scope, out);
    }

    if node.kind != NodeKind::Function {
        for (sname, _) in &state_fields {
            let driver = state_driver_name(sname);
            let _ = writeln!(out, "  self->{sname} = {driver};");
        }
        let _ = writeln!(out, "  self->initialized = true;");
    }
    let _ = writeln!(out, "}}");
    out.push('\n');
}

#[derive(Debug)]
struct Scope {
    inputs: BTreeSet<String>,
    outputs: BTreeSet<String>,
    locals: BTreeSet<String>,
    is_stateful: bool,
}

impl Scope {
    fn ref_var(&self, name: &str) -> String {
        if self.inputs.contains(name) {
            format!("in->{name}")
        } else if self.outputs.contains(name) {
            format!("out->{name}")
        } else if self.locals.contains(name) {
            name.to_string()
        } else {
            name.to_string()
        }
    }
}

fn emit_equation_body(eq: &Equation, scope: &Scope, out: &mut String) {
    if eq.lhs.len() == 1 {
        let lhs = scope.ref_var(&eq.lhs[0]);
        let rhs = emit_expr(&eq.rhs, scope);
        let _ = writeln!(out, "  {lhs} = {rhs};");
    } else if let Expr::Call { node, args } = &eq.rhs {
        let arg_inits = args
            .iter()
            .map(|a| emit_expr(a, scope))
            .collect::<Vec<_>>()
            .join(", ");
        let _ = writeln!(out, "  /* multi-output call to {node}({arg_inits}) */");
        let _ = writeln!(
            out,
            "  /* TODO: bind tuple outputs ({}) — not lowered in this profile. */",
            eq.lhs.join(", ")
        );
    } else {
        let _ = writeln!(out, "  /* unsupported multi-output rhs */");
    }
}

fn emit_expr(expr: &Expr, scope: &Scope) -> String {
    match expr {
        Expr::Const { lit } => match lit {
            Literal::Bool { value } => if *value { "true" } else { "false" }.into(),
            Literal::Int { value } => format!("({})", value),
            Literal::Float { value } => format!("({})", value),
        },
        Expr::Var { name } => scope.ref_var(name),
        Expr::Unary { op, arg } => {
            let a = emit_expr(arg, scope);
            match op {
                UnaryOp::Not => format!("(!{a})"),
                UnaryOp::Neg => format!("(-{a})"),
            }
        }
        Expr::Binary { op, lhs, rhs } => {
            let l = emit_expr(lhs, scope);
            let r = emit_expr(rhs, scope);
            let sym = match op {
                BinOp::And => "&&",
                BinOp::Or => "||",
                BinOp::Xor => "^",
                BinOp::Implies => {
                    return format!("((!{l}) || ({r}))");
                }
                BinOp::Eq => "==",
                BinOp::Neq => "!=",
                BinOp::Lt => "<",
                BinOp::Le => "<=",
                BinOp::Gt => ">",
                BinOp::Ge => ">=",
                BinOp::Add => "+",
                BinOp::Sub => "-",
                BinOp::Mul => "*",
                BinOp::Div => "/",
                BinOp::Mod => "%",
            };
            format!("({l} {sym} {r})")
        }
        Expr::IfThenElse {
            cond,
            then_branch,
            else_branch,
        } => format!(
            "({} ? {} : {})",
            emit_expr(cond, scope),
            emit_expr(then_branch, scope),
            emit_expr(else_branch, scope)
        ),
        Expr::Pre { arg } => {
            // `pre x` reads the previous value of `x` from the state struct.
            // The state field is named after the inner expression (one of the
            // node's outputs/locals/inputs).
            if let Expr::Var { name } = arg.as_ref() {
                format!("self->{}", state_field_name(name))
            } else {
                format!("/* pre of complex expr unsupported: {arg:?} */ 0")
            }
        }
        Expr::Arrow { init, body } => {
            let i = emit_expr(init, scope);
            let b = emit_expr(body, scope);
            let prefix = if scope.is_stateful { "self->initialized" } else { "false" };
            format!("(!{prefix} ? ({i}) : ({b}))")
        }
        Expr::Call { node, args } => {
            let parts = args
                .iter()
                .map(|a| emit_expr(a, scope))
                .collect::<Vec<_>>()
                .join(", ");
            // Inline calls assume the callee is also code-generated as a
            // single-step pure function with all-args-in form. The contract
            // monitor harness is responsible for re-checking these.
            format!("{node}_inline({parts})")
        }
        Expr::Field { base, field } => format!("{}.{field}", emit_expr(base, scope)),
        Expr::Index { base, index } => {
            format!("{}[{}]", emit_expr(base, scope), emit_expr(index, scope))
        }
        Expr::Tuple { .. } => "/* tuple */ 0".into(),
    }
}

fn type_decl(ty: &Type, _name: &str) -> String {
    match ty {
        Type::Array { elem, len } => format!("{}", format!("{}", elem.c_name())) + &format!("[{len}]"),
        other => other.c_name(),
    }
}

fn state_field_name(name: &str) -> String {
    format!("prev_{name}")
}

fn state_driver_name(state_field: &str) -> String {
    // The driver for `prev_x` is the *current* value of `x` after this step.
    if let Some(stripped) = state_field.strip_prefix("prev_") {
        // outputs and locals are accessed by their natural name; here we
        // generate `out->x` since most `pre` consumers reference outputs.
        format!("out->{stripped}")
    } else {
        state_field.to_string()
    }
}

/// Walk a node and collect every `pre x` so we know what state fields to add.
fn node_state_fields(node: &NodeDef) -> Vec<(String, Type)> {
    let mut fields = Vec::new();
    let mut seen = BTreeSet::new();
    let env: std::collections::HashMap<&str, &Type> = node
        .inputs
        .iter()
        .map(|p| (p.name.as_str(), &p.ty))
        .chain(node.outputs.iter().map(|p| (p.name.as_str(), &p.ty)))
        .chain(node.locals.iter().map(|l| (l.name.as_str(), &l.ty)))
        .collect();

    for eq in &node.equations {
        collect_pre_vars(&eq.rhs, &env, &mut fields, &mut seen);
    }
    fields
}

fn collect_pre_vars(
    expr: &Expr,
    env: &std::collections::HashMap<&str, &Type>,
    out: &mut Vec<(String, Type)>,
    seen: &mut BTreeSet<String>,
) {
    match expr {
        Expr::Pre { arg } => {
            if let Expr::Var { name } = arg.as_ref() {
                if seen.insert(name.clone()) {
                    let ty = env
                        .get(name.as_str())
                        .copied()
                        .cloned()
                        .unwrap_or(Type::Bool);
                    out.push((state_field_name(name), ty));
                }
            } else {
                collect_pre_vars(arg, env, out, seen);
            }
        }
        Expr::Unary { arg, .. } => collect_pre_vars(arg, env, out, seen),
        Expr::Binary { lhs, rhs, .. } => {
            collect_pre_vars(lhs, env, out, seen);
            collect_pre_vars(rhs, env, out, seen);
        }
        Expr::IfThenElse {
            cond,
            then_branch,
            else_branch,
        } => {
            collect_pre_vars(cond, env, out, seen);
            collect_pre_vars(then_branch, env, out, seen);
            collect_pre_vars(else_branch, env, out, seen);
        }
        Expr::Arrow { init, body } => {
            collect_pre_vars(init, env, out, seen);
            collect_pre_vars(body, env, out, seen);
        }
        Expr::Call { args, .. } => {
            for a in args {
                collect_pre_vars(a, env, out, seen);
            }
        }
        Expr::Field { base, .. } => collect_pre_vars(base, env, out, seen),
        Expr::Index { base, index } => {
            collect_pre_vars(base, env, out, seen);
            collect_pre_vars(index, env, out, seen);
        }
        Expr::Tuple { items } => {
            for i in items {
                collect_pre_vars(i, env, out, seen);
            }
        }
        Expr::Const { .. } | Expr::Var { .. } => {}
    }
}
