//! OpenLustre Studio: Directional C-Lite emitter (Phase 5).
//!
//! Rules (from the implementation plan, Phase 5):
//! * No malloc/free, no recursion, no function pointers, no pointer arithmetic.
//! * No hidden globals, no implicit casts, no dynamic arrays.
//! * Fixed-width integer types only.
//! * Explicit state structs; explicit init/step entry points.
//! * Explicit input/output structs.
//!
//! Contracts produce *monitors* in a separate translation unit so production
//! C-Lite is not polluted with proof-only logic.
//!
//! ## Calls
//!
//! Every `Expr::Call` in an equation body is lowered into a self-contained
//! block of statements that declares an `{Callee}_Input` / `{Callee}_Output`
//! pair, fills the inputs, and invokes `{Callee}_step`. The call's value is
//! then substituted with `__outN.<output_name>` in the surrounding expression
//! (administrative-normal-form lowering). Stateful operator call sites each
//! get their own `{Callee}_State sub_N` field in the parent's state struct,
//! initialized in the parent's `_init`.

pub mod harness;
pub mod manifest;
pub mod monitor;

use std::collections::{BTreeSet, HashMap};
use std::fmt::Write as _;

use ol_ir::{
    BinOp, Equation, Expr, Literal, NodeDef, NodeKind, Project, Type, TypeBody, TypeDef, UnaryOp,
};

pub use manifest::{load_manifest_dir, ImportedOperator};

#[derive(Debug, Clone)]
pub struct EmittedClite {
    pub header: String,
    pub source: String,
}

pub fn emit_project(project: &Project) -> EmittedClite {
    let mut header = String::new();
    let mut source = String::new();

    let _ = writeln!(header, "/* Generated by OpenLustre Studio. */");
    let _ = writeln!(header, "#ifndef OL_GENERATED_H");
    let _ = writeln!(header, "#define OL_GENERATED_H");
    let _ = writeln!(header, "#include <stdbool.h>");
    let _ = writeln!(header, "#include <stdint.h>");
    let _ = writeln!(header, "#include <string.h>");
    header.push('\n');

    let _ = writeln!(source, "/* Generated by OpenLustre Studio. */");
    let _ = writeln!(source, "#include \"openlustre_generated.h\"");
    source.push('\n');

    // User-declared types must appear before any node struct that uses them.
    for pkg in &project.packages {
        for t in &pkg.types {
            emit_typedef(t, &mut header);
        }
    }

    // Topologically sort nodes so each callee's struct/function is declared
    // before any caller that embeds or invokes it.
    let ordered = topo_sort_nodes(project);
    for node in &ordered {
        emit_node_header(node, project, &mut header);
        emit_node_source(node, project, &mut source);
    }

    let _ = writeln!(header, "#endif /* OL_GENERATED_H */");
    EmittedClite { header, source }
}

fn emit_typedef(t: &TypeDef, out: &mut String) {
    match &t.body {
        TypeBody::Enum(e) => {
            let _ = writeln!(out, "typedef enum {{");
            for (i, v) in e.variants.iter().enumerate() {
                let comma = if i + 1 == e.variants.len() { "" } else { "," };
                let _ = writeln!(out, "  {v}{comma}");
            }
            let _ = writeln!(out, "}} {};", e.name);
            out.push('\n');
        }
        TypeBody::Record { name, fields } => {
            let _ = writeln!(out, "typedef struct {{");
            for f in fields {
                let _ = writeln!(out, "  {};", type_decl(&f.ty, &f.name));
            }
            let _ = writeln!(out, "}} {name};");
            out.push('\n');
        }
        TypeBody::Alias { name, target } => {
            let _ = writeln!(out, "typedef {} {name};", target.c_name());
            out.push('\n');
        }
    }
}

fn topo_sort_nodes<'a>(project: &'a Project) -> Vec<&'a NodeDef> {
    let all: Vec<&NodeDef> = project.all_nodes().collect();
    let mut visited: BTreeSet<String> = BTreeSet::new();
    let mut order: Vec<&NodeDef> = Vec::new();

    fn visit<'a>(
        node: &'a NodeDef,
        project: &'a Project,
        visited: &mut BTreeSet<String>,
        order: &mut Vec<&'a NodeDef>,
    ) {
        if !visited.insert(node.name.clone()) {
            return;
        }
        for eq in &node.equations {
            walk_call_targets(&eq.rhs, &mut |callee_name| {
                if let Some(callee) = project.find_node(callee_name) {
                    visit(callee, project, visited, order);
                }
            });
        }
        order.push(node);
    }

    for n in &all {
        visit(n, project, &mut visited, &mut order);
    }
    order
}

fn walk_call_targets(expr: &Expr, f: &mut impl FnMut(&str)) {
    match expr {
        Expr::Call { node, args } => {
            f(node);
            for a in args {
                walk_call_targets(a, f);
            }
        }
        Expr::Unary { arg, .. } | Expr::Pre { arg } | Expr::Field { base: arg, .. } => {
            walk_call_targets(arg, f)
        }
        Expr::Binary { lhs, rhs, .. } | Expr::Arrow { init: lhs, body: rhs } => {
            walk_call_targets(lhs, f);
            walk_call_targets(rhs, f);
        }
        Expr::IfThenElse {
            cond,
            then_branch,
            else_branch,
        } => {
            walk_call_targets(cond, f);
            walk_call_targets(then_branch, f);
            walk_call_targets(else_branch, f);
        }
        Expr::Index { base, index } => {
            walk_call_targets(base, f);
            walk_call_targets(index, f);
        }
        Expr::Tuple { items } => {
            for i in items {
                walk_call_targets(i, f);
            }
        }
        Expr::Const { .. } | Expr::Var { .. } => {}
    }
}

#[derive(Debug, Clone)]
struct CallSite {
    idx: usize,
    callee_name: String,
}

fn compute_call_sites(node: &NodeDef) -> HashMap<usize, CallSite> {
    let mut map = HashMap::new();
    let mut idx = 0usize;
    for eq in &node.equations {
        walk_calls_assign(&eq.rhs, &mut map, &mut idx);
    }
    map
}

fn walk_calls_assign(expr: &Expr, map: &mut HashMap<usize, CallSite>, idx: &mut usize) {
    if let Expr::Call { node, args } = expr {
        let site = CallSite {
            idx: *idx,
            callee_name: node.clone(),
        };
        map.insert(expr as *const Expr as usize, site);
        *idx += 1;
        for a in args {
            walk_calls_assign(a, map, idx);
        }
        return;
    }
    match expr {
        Expr::Unary { arg, .. } | Expr::Pre { arg } | Expr::Field { base: arg, .. } => {
            walk_calls_assign(arg, map, idx)
        }
        Expr::Binary { lhs, rhs, .. } | Expr::Arrow { init: lhs, body: rhs } => {
            walk_calls_assign(lhs, map, idx);
            walk_calls_assign(rhs, map, idx);
        }
        Expr::IfThenElse {
            cond,
            then_branch,
            else_branch,
        } => {
            walk_calls_assign(cond, map, idx);
            walk_calls_assign(then_branch, map, idx);
            walk_calls_assign(else_branch, map, idx);
        }
        Expr::Index { base, index } => {
            walk_calls_assign(base, map, idx);
            walk_calls_assign(index, map, idx);
        }
        Expr::Tuple { items } => {
            for i in items {
                walk_calls_assign(i, map, idx);
            }
        }
        Expr::Const { .. } | Expr::Var { .. } | Expr::Call { .. } => {}
    }
}

fn emit_node_header(node: &NodeDef, project: &Project, out: &mut String) {
    let prefix = &node.name;
    let _ = writeln!(out, "/* --- {prefix} --- */");

    let _ = writeln!(out, "typedef struct {{");
    for p in &node.inputs {
        let _ = writeln!(out, "  {};", type_decl(&p.ty, &p.name));
    }
    if node.inputs.is_empty() {
        let _ = writeln!(out, "  int8_t _unused;");
    }
    let _ = writeln!(out, "}} {prefix}_Input;");
    out.push('\n');

    let _ = writeln!(out, "typedef struct {{");
    for p in &node.outputs {
        let _ = writeln!(out, "  {};", type_decl(&p.ty, &p.name));
    }
    if node.outputs.is_empty() {
        let _ = writeln!(out, "  int8_t _unused;");
    }
    let _ = writeln!(out, "}} {prefix}_Output;");
    out.push('\n');

    let state_fields = node_state_fields(node);
    let call_sites = compute_call_sites(node);
    let stateful_subs = stateful_subs(node, &call_sites, project);

    let _ = writeln!(out, "typedef struct {{");
    let _ = writeln!(out, "  bool initialized;");
    for (name, ty) in &state_fields {
        let _ = writeln!(out, "  {};", type_decl(ty, name));
    }
    for (idx, callee) in &stateful_subs {
        let _ = writeln!(out, "  {callee}_State sub_{idx};");
    }
    let _ = writeln!(out, "}} {prefix}_State;");
    out.push('\n');

    if node.kind == NodeKind::Function {
        let _ = writeln!(out, "void {prefix}_step(const {prefix}_Input* in, {prefix}_Output* out);");
    } else {
        let _ = writeln!(out, "void {prefix}_init({prefix}_State* self);");
        let _ = writeln!(
            out,
            "void {prefix}_step({prefix}_State* self, const {prefix}_Input* in, {prefix}_Output* out);"
        );
    }
    if node.is_imported() {
        let _ = writeln!(out, "/* imported: implementation provided by external C. */");
    }
    out.push('\n');
}

fn emit_node_source(node: &NodeDef, project: &Project, out: &mut String) {
    if node.is_imported() {
        let _ = writeln!(
            out,
            "/* {0}_step is provided by the imported manifest for {0}. */",
            node.name
        );
        out.push('\n');
        return;
    }

    let prefix = &node.name;
    let state_fields = node_state_fields(node);
    let call_sites = compute_call_sites(node);
    let stateful_subs = stateful_subs(node, &call_sites, project);

    if node.kind != NodeKind::Function {
        let _ = writeln!(out, "void {prefix}_init({prefix}_State* self) {{");
        let _ = writeln!(out, "  memset(self, 0, sizeof(*self));");
        for (idx, callee) in &stateful_subs {
            let _ = writeln!(out, "  {callee}_init(&self->sub_{idx});");
        }
        let _ = writeln!(out, "  self->initialized = false;");
        let _ = writeln!(out, "}}");
        out.push('\n');
    }

    let sig = if node.kind == NodeKind::Function {
        format!("void {prefix}_step(const {prefix}_Input* in, {prefix}_Output* out)")
    } else {
        format!(
            "void {prefix}_step({prefix}_State* self, const {prefix}_Input* in, {prefix}_Output* out)"
        )
    };
    let _ = writeln!(out, "{sig} {{");

    for l in &node.locals {
        // `= {0}` is C's universal zero-initializer — works for scalars,
        // arrays, and structs — so we don't need a per-shape cast.
        let _ = writeln!(out, "  {} = {{0}};", type_decl(&l.ty, &l.name));
    }

    let scope = Scope {
        inputs: node.inputs.iter().map(|p| p.name.clone()).collect(),
        outputs: node.outputs.iter().map(|p| p.name.clone()).collect(),
        locals: node.locals.iter().map(|l| l.name.clone()).collect(),
        is_stateful: node.kind != NodeKind::Function,
    };

    let mut ctx = EmitCtx {
        scope: &scope,
        project,
        call_sites: &call_sites,
    };

    for eq in &node.equations {
        emit_equation_body(eq, &mut ctx, out);
    }

    if node.kind != NodeKind::Function {
        for (sname, _) in &state_fields {
            let driver = state_driver_name(sname, &scope);
            let _ = writeln!(out, "  self->{sname} = {driver};");
        }
        let _ = writeln!(out, "  self->initialized = true;");
    }
    let _ = writeln!(out, "}}");
    out.push('\n');
}

fn stateful_subs<'a>(
    node: &'a NodeDef,
    call_sites: &'a HashMap<usize, CallSite>,
    project: &'a Project,
) -> Vec<(usize, String)> {
    let mut subs: Vec<(usize, String)> = Vec::new();
    for eq in &node.equations {
        collect_stateful(&eq.rhs, call_sites, project, &mut subs);
    }
    subs.sort_by_key(|(i, _)| *i);
    subs
}

fn collect_stateful(
    expr: &Expr,
    call_sites: &HashMap<usize, CallSite>,
    project: &Project,
    out: &mut Vec<(usize, String)>,
) {
    if let Expr::Call { node: callee_name, args } = expr {
        if let Some(callee) = project.find_node(callee_name) {
            if callee.kind == NodeKind::Operator {
                let key = expr as *const Expr as usize;
                if let Some(site) = call_sites.get(&key) {
                    out.push((site.idx, callee_name.clone()));
                }
            }
        }
        for a in args {
            collect_stateful(a, call_sites, project, out);
        }
        return;
    }
    match expr {
        Expr::Unary { arg, .. } | Expr::Pre { arg } | Expr::Field { base: arg, .. } => {
            collect_stateful(arg, call_sites, project, out)
        }
        Expr::Binary { lhs, rhs, .. } | Expr::Arrow { init: lhs, body: rhs } => {
            collect_stateful(lhs, call_sites, project, out);
            collect_stateful(rhs, call_sites, project, out);
        }
        Expr::IfThenElse {
            cond,
            then_branch,
            else_branch,
        } => {
            collect_stateful(cond, call_sites, project, out);
            collect_stateful(then_branch, call_sites, project, out);
            collect_stateful(else_branch, call_sites, project, out);
        }
        Expr::Index { base, index } => {
            collect_stateful(base, call_sites, project, out);
            collect_stateful(index, call_sites, project, out);
        }
        Expr::Tuple { items } => {
            for i in items {
                collect_stateful(i, call_sites, project, out);
            }
        }
        Expr::Const { .. } | Expr::Var { .. } | Expr::Call { .. } => {}
    }
}

#[derive(Debug)]
struct Scope {
    inputs: BTreeSet<String>,
    outputs: BTreeSet<String>,
    locals: BTreeSet<String>,
    is_stateful: bool,
}

impl Scope {
    fn ref_var(&self, name: &str) -> String {
        if self.inputs.contains(name) {
            format!("in->{name}")
        } else if self.outputs.contains(name) {
            format!("out->{name}")
        } else if self.locals.contains(name) {
            name.to_string()
        } else {
            name.to_string()
        }
    }
}

struct EmitCtx<'a> {
    scope: &'a Scope,
    project: &'a Project,
    call_sites: &'a HashMap<usize, CallSite>,
}

fn emit_equation_body(eq: &Equation, ctx: &mut EmitCtx, out: &mut String) {
    // Multi-output: only direct top-level Call binding is supported.
    if eq.lhs.len() > 1 {
        if let Expr::Call { args, .. } = &eq.rhs {
            let key = &eq.rhs as *const Expr as usize;
            let site = ctx
                .call_sites
                .get(&key)
                .expect("multi-output call missing site index");
            let callee = ctx
                .project
                .find_node(&site.callee_name)
                .expect("callee resolved");
            let (stmts, arg_strs) = lower_args(args, ctx);
            for s in stmts {
                out.push_str(&s);
            }
            emit_call_block(callee, site.idx, &arg_strs, out);
            for (lhs, p) in eq.lhs.iter().zip(callee.outputs.iter()) {
                let l = ctx.scope.ref_var(lhs);
                let _ = writeln!(out, "  {l} = __out{}.{};", site.idx, p.name);
            }
        } else {
            let _ = writeln!(out, "  /* unsupported multi-output rhs */");
        }
        return;
    }

    let (stmts, rhs_expr) = lower_anf(&eq.rhs, ctx);
    for s in stmts {
        out.push_str(&s);
    }
    let lhs = ctx.scope.ref_var(&eq.lhs[0]);
    let _ = writeln!(out, "  {lhs} = {rhs_expr};");
}

fn lower_args(args: &[Expr], ctx: &mut EmitCtx) -> (Vec<String>, Vec<String>) {
    let mut all_stmts = Vec::new();
    let mut arg_strs = Vec::new();
    for a in args {
        let (s, e) = lower_anf(a, ctx);
        all_stmts.extend(s);
        arg_strs.push(e);
    }
    (all_stmts, arg_strs)
}

fn emit_call_block(callee: &NodeDef, idx: usize, arg_strs: &[String], out: &mut String) {
    let name = &callee.name;
    let _ = writeln!(out, "  {name}_Input __in{idx};");
    let _ = writeln!(out, "  {name}_Output __out{idx};");
    for (p, a) in callee.inputs.iter().zip(arg_strs.iter()) {
        let _ = writeln!(out, "  __in{idx}.{} = {};", p.name, a);
    }
    if callee.is_function() {
        let _ = writeln!(out, "  {name}_step(&__in{idx}, &__out{idx});");
    } else {
        let _ = writeln!(out, "  {name}_step(&self->sub_{idx}, &__in{idx}, &__out{idx});");
    }
}

/// Lower `expr` into (preceding statements, substituted expression). Calls are
/// hoisted into named struct pairs (`__inN` / `__outN`) and substituted with
/// `__outN.<output_name>` in the surrounding expression.
fn lower_anf(expr: &Expr, ctx: &mut EmitCtx) -> (Vec<String>, String) {
    match expr {
        Expr::Const { lit } => {
            let s = match lit {
                Literal::Bool { value } => if *value { "true" } else { "false" }.into(),
                Literal::Int { value } => format!("({value})"),
                Literal::Float { value } => format!("({value})"),
            };
            (vec![], s)
        }
        Expr::Var { name } => (vec![], ctx.scope.ref_var(name)),
        Expr::Unary { op, arg } => {
            let (s, a) = lower_anf(arg, ctx);
            let r = match op {
                UnaryOp::Not => format!("(!{a})"),
                UnaryOp::Neg => format!("(-{a})"),
            };
            (s, r)
        }
        Expr::Binary { op, lhs, rhs } => {
            let (mut s, l) = lower_anf(lhs, ctx);
            let (sr, r) = lower_anf(rhs, ctx);
            s.extend(sr);
            let sym = match op {
                BinOp::And => "&&",
                BinOp::Or => "||",
                BinOp::Xor => "^",
                BinOp::Implies => return (s, format!("((!{l}) || ({r}))")),
                BinOp::Eq => "==",
                BinOp::Neq => "!=",
                BinOp::Lt => "<",
                BinOp::Le => "<=",
                BinOp::Gt => ">",
                BinOp::Ge => ">=",
                BinOp::Add => "+",
                BinOp::Sub => "-",
                BinOp::Mul => "*",
                BinOp::Div => "/",
                BinOp::Mod => "%",
            };
            (s, format!("({l} {sym} {r})"))
        }
        Expr::IfThenElse {
            cond,
            then_branch,
            else_branch,
        } => {
            let (mut s, c) = lower_anf(cond, ctx);
            let (st, t) = lower_anf(then_branch, ctx);
            let (se, e) = lower_anf(else_branch, ctx);
            s.extend(st);
            s.extend(se);
            (s, format!("({c} ? {t} : {e})"))
        }
        Expr::Pre { arg } => {
            if let Expr::Var { name } = arg.as_ref() {
                (vec![], format!("self->{}", state_field_name(name)))
            } else {
                (vec![], format!("/* pre of complex expr unsupported: {arg:?} */ 0"))
            }
        }
        Expr::Arrow { init, body } => {
            let (mut s, i) = lower_anf(init, ctx);
            let (sb, b) = lower_anf(body, ctx);
            s.extend(sb);
            let prefix = if ctx.scope.is_stateful { "self->initialized" } else { "false" };
            (s, format!("(!{prefix} ? ({i}) : ({b}))"))
        }
        Expr::Call { args, .. } => {
            let key = expr as *const Expr as usize;
            let site = ctx
                .call_sites
                .get(&key)
                .expect("call site index not registered");
            let callee = ctx
                .project
                .find_node(&site.callee_name)
                .expect("callee resolves");

            let (mut s, arg_strs) = lower_args(args, ctx);
            let mut block = String::new();
            emit_call_block(callee, site.idx, &arg_strs, &mut block);
            s.push(block);

            if callee.outputs.len() == 1 {
                (s, format!("__out{}.{}", site.idx, callee.outputs[0].name))
            } else {
                // Non-top-level multi-output call — return only the first
                // output; the surrounding equation should have used a tuple
                // binding. Emit a comment so it's visible in the generated C.
                (
                    s,
                    format!(
                        "/* multi-output call used in expression position */ __out{}.{}",
                        site.idx, callee.outputs[0].name
                    ),
                )
            }
        }
        Expr::Field { base, field } => {
            let (s, b) = lower_anf(base, ctx);
            (s, format!("{b}.{field}"))
        }
        Expr::Index { base, index } => {
            let (mut s, b) = lower_anf(base, ctx);
            let (si, i) = lower_anf(index, ctx);
            s.extend(si);
            (s, format!("{b}[{i}]"))
        }
        Expr::Tuple { .. } => (vec![], "/* tuple */ 0".into()),
    }
}

/// Emit a complete C declarator (`<type> <name>`, with array brackets after the
/// name as C requires). Caller appends `;` or `= ...` etc.
fn type_decl(ty: &Type, name: &str) -> String {
    match ty {
        Type::Array { elem, len } => format!("{} {name}[{len}]", elem.c_name()),
        other => format!("{} {name}", other.c_name()),
    }
}

fn state_field_name(name: &str) -> String {
    format!("prev_{name}")
}

fn state_driver_name(state_field: &str, scope: &Scope) -> String {
    if let Some(stripped) = state_field.strip_prefix("prev_") {
        // The "previous value" for a `pre x` is the current cycle's `x` after
        // the step body runs. Resolve where that name lives so the driver is
        // valid C — inputs come from `in->`, outputs from `out->`, and locals
        // are plain identifiers.
        scope.ref_var(stripped)
    } else {
        state_field.to_string()
    }
}

/// Walk a node and collect every `pre x` so we know what state fields to add.
fn node_state_fields(node: &NodeDef) -> Vec<(String, Type)> {
    let mut fields = Vec::new();
    let mut seen = BTreeSet::new();
    let env: std::collections::HashMap<&str, &Type> = node
        .inputs
        .iter()
        .map(|p| (p.name.as_str(), &p.ty))
        .chain(node.outputs.iter().map(|p| (p.name.as_str(), &p.ty)))
        .chain(node.locals.iter().map(|l| (l.name.as_str(), &l.ty)))
        .collect();

    for eq in &node.equations {
        collect_pre_vars(&eq.rhs, &env, &mut fields, &mut seen);
    }
    fields
}

fn collect_pre_vars(
    expr: &Expr,
    env: &std::collections::HashMap<&str, &Type>,
    out: &mut Vec<(String, Type)>,
    seen: &mut BTreeSet<String>,
) {
    match expr {
        Expr::Pre { arg } => {
            if let Expr::Var { name } = arg.as_ref() {
                if seen.insert(name.clone()) {
                    let ty = env
                        .get(name.as_str())
                        .copied()
                        .cloned()
                        .unwrap_or(Type::Bool);
                    out.push((state_field_name(name), ty));
                }
            } else {
                collect_pre_vars(arg, env, out, seen);
            }
        }
        Expr::Unary { arg, .. } => collect_pre_vars(arg, env, out, seen),
        Expr::Binary { lhs, rhs, .. } => {
            collect_pre_vars(lhs, env, out, seen);
            collect_pre_vars(rhs, env, out, seen);
        }
        Expr::IfThenElse {
            cond,
            then_branch,
            else_branch,
        } => {
            collect_pre_vars(cond, env, out, seen);
            collect_pre_vars(then_branch, env, out, seen);
            collect_pre_vars(else_branch, env, out, seen);
        }
        Expr::Arrow { init, body } => {
            collect_pre_vars(init, env, out, seen);
            collect_pre_vars(body, env, out, seen);
        }
        Expr::Call { args, .. } => {
            for a in args {
                collect_pre_vars(a, env, out, seen);
            }
        }
        Expr::Field { base, .. } => collect_pre_vars(base, env, out, seen),
        Expr::Index { base, index } => {
            collect_pre_vars(base, env, out, seen);
            collect_pre_vars(index, env, out, seen);
        }
        Expr::Tuple { items } => {
            for i in items {
                collect_pre_vars(i, env, out, seen);
            }
        }
        Expr::Const { .. } | Expr::Var { .. } => {}
    }
}
