//! OpenLustre Studio: Directional C-Lite emitter (Phase 5).
//!
//! Rules (from the implementation plan, Phase 5):
//! * No malloc/free, no recursion, no function pointers, no pointer arithmetic.
//! * No hidden globals, no implicit casts, no dynamic arrays.
//! * Fixed-width integer types only.
//! * Explicit state structs; explicit init/step entry points.
//! * Explicit input/output structs.
//!
//! Contracts produce *monitors* in a separate translation unit so production
//! C-Lite is not polluted with proof-only logic.
//!
//! ## Calls
//!
//! Every `Expr::Call` in an equation body is lowered into a self-contained
//! block of statements that declares an `{Callee}_Input` / `{Callee}_Output`
//! pair, fills the inputs, and invokes `{Callee}_step`. The call's value is
//! then substituted with `__outN.<output_name>` in the surrounding expression
//! (administrative-normal-form lowering). Stateful operator call sites each
//! get their own `{Callee}_State sub_N` field in the parent's state struct,
//! initialized in the parent's `_init`.

pub mod harness;
pub mod imported;
pub mod manifest;
pub mod monitor;

use std::collections::{BTreeSet, HashMap};
use std::fmt::Write as _;

use ol_ir::{
    BinOp, Equation, Expr, Literal, NodeDef, NodeKind, Project, Type, TypeBody, TypeDef, UnaryOp,
};

pub use imported::{emit_wrapper, expected_prototype, BuildPlan, ImportedWrapper};
pub use manifest::{load_manifest_dir, ImportedOperator};

#[derive(Debug, Clone)]
pub struct EmittedClite {
    pub header: String,
    pub source: String,
}

pub fn emit_project(project: &Project) -> EmittedClite {
    let mut header = String::new();
    let mut source = String::new();

    let _ = writeln!(header, "/* Generated by OpenLustre Studio. */");
    let _ = writeln!(header, "#ifndef OL_GENERATED_H");
    let _ = writeln!(header, "#define OL_GENERATED_H");
    let _ = writeln!(header, "#include <stdbool.h>");
    let _ = writeln!(header, "#include <stdint.h>");
    let _ = writeln!(header, "#include <string.h>");
    header.push('\n');

    let _ = writeln!(source, "/* Generated by OpenLustre Studio. */");
    let _ = writeln!(source, "#include \"openlustre_generated.h\"");
    // Float intrinsics (sqrt, sin, …) lower to <math.h> calls.
    let _ = writeln!(source, "#include <math.h>");
    // A debug build (-DOL_DEBUG) enables log-message probes; the driver sets
    // `ol_dbg_print` on the cycles it wants them printed. Off by default, so
    // production C and the equivalence tests are untouched.
    let _ = writeln!(source, "#ifdef OL_DEBUG");
    let _ = writeln!(source, "#include <stdio.h>");
    let _ = writeln!(source, "extern int ol_dbg_print;");
    let _ = writeln!(source, "#endif");
    source.push('\n');

    // User-declared types must appear before any node struct that uses them.
    for pkg in &project.packages {
        for t in &pkg.types {
            emit_typedef(t, &mut header);
        }
    }

    // Constants render as `#define` so they're usable in C initializers and
    // freely referenced from node bodies as bare identifiers.
    for pkg in &project.packages {
        for c in &pkg.constants {
            emit_const(c, &mut header);
        }
        if !pkg.constants.is_empty() {
            header.push('\n');
        }
    }

    // Topologically sort nodes so each callee's struct/function is declared
    // before any caller that embeds or invokes it.
    let ordered = topo_sort_nodes(project);
    for node in &ordered {
        emit_node_header(node, project, &mut header);
        emit_node_source(node, project, &mut source);
    }

    let _ = writeln!(header, "#endif /* OL_GENERATED_H */");
    EmittedClite { header, source }
}

fn emit_const(c: &ol_ir::ConstDef, out: &mut String) {
    match &c.value {
        // Composite constants need real storage so they can be indexed or
        // field-accessed: a `#define` of a braced initializer is not a usable
        // lvalue. Scalars (and enum/expression constants) stay as `#define`,
        // keeping every existing constant byte-identical.
        Expr::Array { .. } | Expr::Struct { .. } => {
            let _ = writeln!(
                out,
                "static const {} = {};",
                type_decl(&c.ty, &c.name),
                format_const_expr(&c.value)
            );
        }
        _ => {
            let _ = writeln!(out, "#define {} ({})", c.name, format_const_expr(&c.value));
        }
    }
}

/// Render a constant's Expr in C syntax. Handles the subset of Expr that can
/// appear in a well-formed const value: literals, var references (to other
/// consts / enum variants), unary, binary, and if/then/else.
fn format_const_expr(expr: &Expr) -> String {
    match expr {
        Expr::Const { lit } => match lit {
            Literal::Bool { value } => if *value { "true" } else { "false" }.into(),
            Literal::Int { value } => format!("({value})"),
            Literal::Float { value } => format!("({value})"),
            // A char is an int byte in C.
            Literal::Char { value } => format!("({value})"),
        },
        // Array / record initializer lists (`{1, 2, 3}`, `{.x = 1, .y = 2}`),
        // used as the RHS of a `static const` definition by `emit_const`.
        Expr::Array { items } => {
            let parts = items.iter().map(format_const_expr).collect::<Vec<_>>().join(", ");
            format!("{{{parts}}}")
        }
        Expr::Struct { fields, .. } => {
            let parts = fields
                .iter()
                .map(|fi| format!(".{} = {}", fi.field, format_const_expr(&fi.value)))
                .collect::<Vec<_>>()
                .join(", ");
            format!("{{{parts}}}")
        }
        Expr::Var { name } => name.clone(),
        Expr::Unary { op, arg } => {
            let a = format_const_expr(arg);
            match op {
                UnaryOp::Not => format!("(!{a})"),
                UnaryOp::Neg => format!("(-{a})"),
            }
        }
        Expr::Binary { op, lhs, rhs } => {
            let l = format_const_expr(lhs);
            let r = format_const_expr(rhs);
            let sym = match op {
                BinOp::And => "&&",
                BinOp::Or => "||",
                BinOp::Xor => "^",
                BinOp::Implies => return format!("((!{l}) || ({r}))"),
                BinOp::Eq => "==",
                BinOp::Neq => "!=",
                BinOp::Lt => "<",
                BinOp::Le => "<=",
                BinOp::Gt => ">",
                BinOp::Ge => ">=",
                BinOp::Add => "+",
                BinOp::Sub => "-",
                BinOp::Mul => "*",
                BinOp::Div => "/",
                BinOp::Mod => "%",
                BinOp::BitAnd => "&",
                BinOp::BitOr => "|",
                BinOp::BitXor => "^",
                BinOp::Shl => "<<",
                BinOp::Shr => ">>",
            };
            format!("({l} {sym} {r})")
        }
        Expr::IfThenElse { cond, then_branch, else_branch } => format!(
            "({} ? {} : {})",
            format_const_expr(cond),
            format_const_expr(then_branch),
            format_const_expr(else_branch)
        ),
        _ => "/* unsupported in const */ 0".into(),
    }
}

fn emit_typedef(t: &TypeDef, out: &mut String) {
    match &t.body {
        TypeBody::Enum(e) => {
            let _ = writeln!(out, "typedef enum {{");
            for (i, v) in e.variants.iter().enumerate() {
                let comma = if i + 1 == e.variants.len() { "" } else { "," };
                let _ = writeln!(out, "  {v}{comma}");
            }
            let _ = writeln!(out, "}} {};", e.name);
            out.push('\n');
        }
        TypeBody::Record { name, fields } => {
            let _ = writeln!(out, "typedef struct {{");
            for f in fields {
                let _ = writeln!(out, "  {};", type_decl(&f.ty, &f.name));
            }
            let _ = writeln!(out, "}} {name};");
            out.push('\n');
        }
        TypeBody::Alias { name, target } => {
            let _ = writeln!(out, "typedef {} {name};", target.c_name());
            out.push('\n');
        }
    }
}

fn topo_sort_nodes<'a>(project: &'a Project) -> Vec<&'a NodeDef> {
    let all: Vec<&NodeDef> = project.all_nodes().collect();
    let mut visited: BTreeSet<String> = BTreeSet::new();
    let mut order: Vec<&NodeDef> = Vec::new();

    fn visit<'a>(
        node: &'a NodeDef,
        project: &'a Project,
        visited: &mut BTreeSet<String>,
        order: &mut Vec<&'a NodeDef>,
    ) {
        if !visited.insert(node.name.clone()) {
            return;
        }
        for eq in &node.equations {
            walk_call_targets(&eq.rhs, &mut |callee_name| {
                if let Some(callee) = project.find_node(callee_name) {
                    visit(callee, project, visited, order);
                }
            });
        }
        order.push(node);
    }

    for n in &all {
        visit(n, project, &mut visited, &mut order);
    }
    order
}

fn walk_call_targets(expr: &Expr, f: &mut impl FnMut(&str)) {
    match expr {
        Expr::Call { node, args } => {
            f(node);
            for a in args {
                walk_call_targets(a, f);
            }
        }
        Expr::Unary { arg, .. }
        | Expr::Pre { arg }
        | Expr::Field { base: arg, .. }
        | Expr::Cast { arg, .. } => walk_call_targets(arg, f),
        Expr::Binary { lhs, rhs, .. } | Expr::Arrow { init: lhs, body: rhs } => {
            walk_call_targets(lhs, f);
            walk_call_targets(rhs, f);
        }
        Expr::IfThenElse {
            cond,
            then_branch,
            else_branch,
        } => {
            walk_call_targets(cond, f);
            walk_call_targets(then_branch, f);
            walk_call_targets(else_branch, f);
        }
        Expr::Index { base, index } => {
            walk_call_targets(base, f);
            walk_call_targets(index, f);
        }
        Expr::Tuple { items } | Expr::Array { items } => {
            for i in items {
                walk_call_targets(i, f);
            }
        }
        Expr::Struct { fields, .. } => {
            for fi in fields {
                walk_call_targets(&fi.value, f);
            }
        }
        Expr::When { arg, .. } => walk_call_targets(arg, f),
        Expr::Merge { on_true, on_false, .. } => {
            walk_call_targets(on_true, f);
            walk_call_targets(on_false, f);
        }
        // The iterated function is a call target — topo-sort must emit it
        // before this node, exactly like a direct `Call`.
        Expr::Iterate { node, init, arrays, .. } => {
            f(node);
            if let Some(i) = init {
                walk_call_targets(i, f);
            }
            for a in arrays {
                walk_call_targets(a, f);
            }
        }
        // Intrinsics are not call targets, but their operands may contain calls.
        Expr::Intrinsic { args, .. } => {
            for a in args {
                walk_call_targets(a, f);
            }
        }
        Expr::Const { .. } | Expr::Var { .. } => {}
    }
}

#[derive(Debug, Clone)]
struct CallSite {
    idx: usize,
    callee_name: String,
}

fn compute_call_sites(node: &NodeDef) -> HashMap<usize, CallSite> {
    let mut map = HashMap::new();
    let mut idx = 0usize;
    for eq in &node.equations {
        walk_calls_assign(&eq.rhs, &mut map, &mut idx);
    }
    map
}

fn walk_calls_assign(expr: &Expr, map: &mut HashMap<usize, CallSite>, idx: &mut usize) {
    if let Expr::Call { node, args } = expr {
        let site = CallSite {
            idx: *idx,
            callee_name: node.clone(),
        };
        map.insert(expr as *const Expr as usize, site);
        *idx += 1;
        for a in args {
            walk_calls_assign(a, map, idx);
        }
        return;
    }
    match expr {
        Expr::Unary { arg, .. }
        | Expr::Pre { arg }
        | Expr::Field { base: arg, .. }
        | Expr::Cast { arg, .. } => walk_calls_assign(arg, map, idx),
        Expr::Binary { lhs, rhs, .. } | Expr::Arrow { init: lhs, body: rhs } => {
            walk_calls_assign(lhs, map, idx);
            walk_calls_assign(rhs, map, idx);
        }
        Expr::IfThenElse {
            cond,
            then_branch,
            else_branch,
        } => {
            walk_calls_assign(cond, map, idx);
            walk_calls_assign(then_branch, map, idx);
            walk_calls_assign(else_branch, map, idx);
        }
        Expr::Index { base, index } => {
            walk_calls_assign(base, map, idx);
            walk_calls_assign(index, map, idx);
        }
        Expr::Tuple { items } | Expr::Array { items } => {
            for i in items {
                walk_calls_assign(i, map, idx);
            }
        }
        Expr::Struct { fields, .. } => {
            for fi in fields {
                walk_calls_assign(&fi.value, map, idx);
            }
        }
        Expr::When { arg, .. } => walk_calls_assign(arg, map, idx),
        Expr::Merge { on_true, on_false, .. } => {
            walk_calls_assign(on_true, map, idx);
            walk_calls_assign(on_false, map, idx);
        }
        // The iterated function is invoked statelessly inside the loop, not a
        // call site here; but its operands may contain calls.
        Expr::Iterate { init, arrays, .. } => {
            if let Some(i) = init {
                walk_calls_assign(i, map, idx);
            }
            for a in arrays {
                walk_calls_assign(a, map, idx);
            }
        }
        Expr::Intrinsic { args, .. } => {
            for a in args {
                walk_calls_assign(a, map, idx);
            }
        }
        Expr::Const { .. } | Expr::Var { .. } | Expr::Call { .. } => {}
    }
}

fn emit_node_header(node: &NodeDef, project: &Project, out: &mut String) {
    let prefix = &node.name;
    let _ = writeln!(out, "/* --- {prefix} --- */");

    let _ = writeln!(out, "typedef struct {{");
    for p in &node.inputs {
        let _ = writeln!(out, "  {};", type_decl(&p.ty, &c_ident(&p.name)));
    }
    if node.inputs.is_empty() {
        let _ = writeln!(out, "  int8_t _unused;");
    }
    let _ = writeln!(out, "}} {prefix}_Input;");
    out.push('\n');

    let _ = writeln!(out, "typedef struct {{");
    for p in &node.outputs {
        let _ = writeln!(out, "  {};", type_decl(&p.ty, &c_ident(&p.name)));
    }
    if node.outputs.is_empty() {
        let _ = writeln!(out, "  int8_t _unused;");
    }
    let _ = writeln!(out, "}} {prefix}_Output;");
    out.push('\n');

    let state_fields = node_state_fields(node);
    let call_sites = compute_call_sites(node);
    let stateful_subs = stateful_subs(node, &call_sites, project);

    let _ = writeln!(out, "typedef struct {{");
    let _ = writeln!(out, "  bool initialized;");
    for (name, ty) in &state_fields {
        let _ = writeln!(out, "  {};", type_decl(ty, name));
    }
    for (idx, callee) in &stateful_subs {
        let _ = writeln!(out, "  {callee}_State sub_{idx};");
    }
    let clocks = node_clocks(node);
    for (name, ty) in clocks.held_fields(node) {
        let _ = writeln!(out, "  {}; /* held through inactive cycles */", type_decl(&ty, &name));
    }
    for (i, ck) in clocks.info.chains.iter().enumerate() {
        let _ = writeln!(out, "  bool clk{i}_ticked; /* {} */", ck.key());
    }
    let _ = writeln!(out, "}} {prefix}_State;");
    out.push('\n');

    if node.kind == NodeKind::Function {
        let _ = writeln!(out, "void {prefix}_step(const {prefix}_Input* in, {prefix}_Output* out);");
    } else {
        let _ = writeln!(out, "void {prefix}_init({prefix}_State* self);");
        let _ = writeln!(
            out,
            "void {prefix}_step({prefix}_State* self, const {prefix}_Input* in, {prefix}_Output* out);"
        );
    }
    if node.is_imported() {
        let _ = writeln!(out, "/* imported: implementation provided by external C. */");
    }
    out.push('\n');
}

fn emit_node_source(node: &NodeDef, project: &Project, out: &mut String) {
    if node.is_imported() {
        let _ = writeln!(
            out,
            "/* {0}_step is provided by the imported manifest for {0}. */",
            node.name
        );
        out.push('\n');
        return;
    }

    let prefix = &node.name;
    let state_fields = node_state_fields(node);
    let call_sites = compute_call_sites(node);
    let stateful_subs = stateful_subs(node, &call_sites, project);

    if node.kind != NodeKind::Function {
        let _ = writeln!(out, "void {prefix}_init({prefix}_State* self) {{");
        let _ = writeln!(out, "  memset(self, 0, sizeof(*self));");
        for (idx, callee) in &stateful_subs {
            let _ = writeln!(out, "  {callee}_init(&self->sub_{idx});");
        }
        let _ = writeln!(out, "  self->initialized = false;");
        let _ = writeln!(out, "}}");
        out.push('\n');
    }

    let sig = if node.kind == NodeKind::Function {
        format!("void {prefix}_step(const {prefix}_Input* in, {prefix}_Output* out)")
    } else {
        format!(
            "void {prefix}_step({prefix}_State* self, const {prefix}_Input* in, {prefix}_Output* out)"
        )
    };
    let _ = writeln!(out, "{sig} {{");

    for l in &node.locals {
        // `= {0}` is C's universal zero-initializer — works for scalars,
        // arrays, and structs — so we don't need a per-shape cast.
        let _ = writeln!(out, "  {} = {{0}};", type_decl(&l.ty, &c_ident(&l.name)));
    }

    let scope = Scope {
        inputs: node.inputs.iter().map(|p| p.name.clone()).collect(),
        outputs: node.outputs.iter().map(|p| p.name.clone()).collect(),
        locals: node.locals.iter().map(|l| l.name.clone()).collect(),
        is_stateful: node.kind != NodeKind::Function,
    };

    let clocks = node_clocks(node);
    let types: HashMap<String, Type> = node
        .inputs
        .iter()
        .map(|p| (p.name.clone(), p.ty.clone()))
        .chain(node.outputs.iter().map(|p| (p.name.clone(), p.ty.clone())))
        .chain(node.locals.iter().map(|l| (l.name.clone(), l.ty.clone())))
        .collect();
    let mut ctx = EmitCtx {
        scope: &scope,
        project,
        call_sites: &call_sites,
        clocks: &clocks,
        types: &types,
        iter_seq: 0,
    };

    // C assignments execute top-to-bottom, so equations must be emitted in
    // dependency order — declaration order would read stale values for
    // forward references. On a genuine combinational cycle (already an error
    // at typecheck time) fall back to declaration order so the emitter still
    // produces inspectable output.
    let order = ol_ir::evaluation_order(node)
        .unwrap_or_else(|_| (0..node.equations.len()).collect());
    for &i in &order {
        let eq = &node.equations[i];
        let eq_clock = clocks
            .info
            .equation_clocks
            .get(i)
            .cloned()
            .unwrap_or(ol_ir::Clock::Base);
        if eq_clock.is_base() || node.kind == NodeKind::Function {
            emit_equation_body(eq, &mut ctx, out);
            continue;
        }
        // Clocked equation: run only on active cycles, hold the lhs through
        // inactive ones — exactly the simulator's gating.
        let cond = clocks.chain_cond(&eq_clock, &scope);
        let _ = writeln!(out, "  if ({cond}) {{");
        let mut body = String::new();
        emit_equation_body(eq, &mut ctx, &mut body);
        for line in body.lines() {
            let _ = writeln!(out, "  {line}");
        }
        for l in &eq.lhs {
            let _ = writeln!(out, "    self->held_{} = {};", c_ident(l), scope.ref_var(l));
        }
        let _ = writeln!(out, "  }} else {{");
        for l in &eq.lhs {
            let _ = writeln!(out, "    {} = self->held_{};", scope.ref_var(l), c_ident(l));
        }
        let _ = writeln!(out, "  }}");
    }

    if node.kind != NodeKind::Function {
        for (sname, _) in &state_fields {
            let driver = state_driver_name(sname, &scope);
            let _ = writeln!(out, "  self->{sname} = {driver};");
        }
        for (i, ck) in clocks.info.chains.iter().enumerate() {
            let cond = clocks.chain_cond(ck, &scope);
            let _ = writeln!(out, "  if ({cond}) self->clk{i}_ticked = true;");
        }
        let _ = writeln!(out, "  self->initialized = true;");
    }
    // Debug log probes (SCADE "log messages"): printed only in a debug build,
    // and only on the cycles the driver flags — so production C is untouched
    // and the dual-backend equivalence tests never see them.
    if !node.probes.is_empty() {
        let _ = writeln!(out, "#ifdef OL_DEBUG");
        let _ = writeln!(out, "  if (ol_dbg_print) {{");
        for probe in &node.probes {
            let _ = writeln!(out, "    {}", probe_printf(probe, &types, &scope));
        }
        let _ = writeln!(out, "  }}");
        let _ = writeln!(out, "#endif");
    }
    let _ = writeln!(out, "}}");
    out.push('\n');
}

/// A `printf` for one log probe, formatted by the variable's type. Arrays and
/// records fall through to a placeholder rather than printing garbage.
fn probe_printf(probe: &ol_ir::Probe, types: &HashMap<String, Type>, scope: &Scope) -> String {
    let r = scope.ref_var(&probe.var);
    let label = probe.label.replace('\\', "\\\\").replace('"', "\\\"");
    match types.get(&probe.var) {
        Some(Type::Bool) => format!("printf(\"{label}: %s\\n\", {r} ? \"true\" : \"false\");"),
        Some(t) if t.is_float() => format!("printf(\"{label}: %g\\n\", (double) {r});"),
        Some(t) if t.is_integer() => format!("printf(\"{label}: %lld\\n\", (long long) {r});"),
        _ => format!("printf(\"{label}: (unprintable)\\n\");"),
    }
}

fn stateful_subs<'a>(
    node: &'a NodeDef,
    call_sites: &'a HashMap<usize, CallSite>,
    project: &'a Project,
) -> Vec<(usize, String)> {
    let mut subs: Vec<(usize, String)> = Vec::new();
    for eq in &node.equations {
        collect_stateful(&eq.rhs, call_sites, project, &mut subs);
    }
    subs.sort_by_key(|(i, _)| *i);
    subs
}

fn collect_stateful(
    expr: &Expr,
    call_sites: &HashMap<usize, CallSite>,
    project: &Project,
    out: &mut Vec<(usize, String)>,
) {
    if let Expr::Call { node: callee_name, args } = expr {
        if let Some(callee) = project.find_node(callee_name) {
            if callee.kind == NodeKind::Operator {
                let key = expr as *const Expr as usize;
                if let Some(site) = call_sites.get(&key) {
                    out.push((site.idx, callee_name.clone()));
                }
            }
        }
        for a in args {
            collect_stateful(a, call_sites, project, out);
        }
        return;
    }
    match expr {
        Expr::Unary { arg, .. }
        | Expr::Pre { arg }
        | Expr::Field { base: arg, .. }
        | Expr::Cast { arg, .. } => collect_stateful(arg, call_sites, project, out),
        Expr::Binary { lhs, rhs, .. } | Expr::Arrow { init: lhs, body: rhs } => {
            collect_stateful(lhs, call_sites, project, out);
            collect_stateful(rhs, call_sites, project, out);
        }
        Expr::IfThenElse {
            cond,
            then_branch,
            else_branch,
        } => {
            collect_stateful(cond, call_sites, project, out);
            collect_stateful(then_branch, call_sites, project, out);
            collect_stateful(else_branch, call_sites, project, out);
        }
        Expr::Index { base, index } => {
            collect_stateful(base, call_sites, project, out);
            collect_stateful(index, call_sites, project, out);
        }
        Expr::Tuple { items } | Expr::Array { items } => {
            for i in items {
                collect_stateful(i, call_sites, project, out);
            }
        }
        Expr::Struct { fields, .. } => {
            for fi in fields {
                collect_stateful(&fi.value, call_sites, project, out);
            }
        }
        Expr::When { arg, .. } => collect_stateful(arg, call_sites, project, out),
        Expr::Merge { on_true, on_false, .. } => {
            collect_stateful(on_true, call_sites, project, out);
            collect_stateful(on_false, call_sites, project, out);
        }
        // The iterated function is stateless (typecheck enforces it), so no
        // sub-state — only its operands can carry stateful calls.
        Expr::Iterate { init, arrays, .. } => {
            if let Some(i) = init {
                collect_stateful(i, call_sites, project, out);
            }
            for a in arrays {
                collect_stateful(a, call_sites, project, out);
            }
        }
        // Intrinsics are pure; only their operands can carry stateful calls.
        Expr::Intrinsic { args, .. } => {
            for a in args {
                collect_stateful(a, call_sites, project, out);
            }
        }
        Expr::Const { .. } | Expr::Var { .. } | Expr::Call { .. } => {}
    }
}

/// Clock support for the generated C, mirroring the simulator exactly:
/// a clocked equation becomes a guarded `if` whose lhs holds its previous
/// value through inactive cycles (a `held_*` state field), and a clocked
/// `->` consults a per-chain `clkN_ticked` flag instead of the node-wide
/// `initialized` flag — `init` on the chain's first tick, `body` after.
struct NodeClocks {
    info: ol_ir::ClockInfo,
    /// Chain key ([`ol_ir::Clock::key`]) -> state-field name.
    chain_fields: HashMap<String, String>,
}

fn node_clocks(node: &NodeDef) -> NodeClocks {
    let info = if ol_ir::node_uses_clocks(node) {
        ol_ir::infer_clocks(node)
    } else {
        ol_ir::ClockInfo::default()
    };
    let chain_fields = info
        .chains
        .iter()
        .enumerate()
        .map(|(i, c)| (c.key(), format!("clk{i}_ticked")))
        .collect();
    NodeClocks { info, chain_fields }
}

impl NodeClocks {
    /// Held-value state fields: one per lhs of every clocked equation.
    fn held_fields(&self, node: &NodeDef) -> Vec<(String, Type)> {
        let env: HashMap<&str, &Type> = node
            .inputs
            .iter()
            .map(|p| (p.name.as_str(), &p.ty))
            .chain(node.outputs.iter().map(|p| (p.name.as_str(), &p.ty)))
            .chain(node.locals.iter().map(|l| (l.name.as_str(), &l.ty)))
            .collect();
        let mut out = Vec::new();
        let mut seen = BTreeSet::new();
        for (i, eq) in node.equations.iter().enumerate() {
            let clocked = self
                .info
                .equation_clocks
                .get(i)
                .map(|c| !c.is_base())
                .unwrap_or(false);
            if !clocked {
                continue;
            }
            for l in &eq.lhs {
                if seen.insert(l.clone()) {
                    let ty = env.get(l.as_str()).copied().cloned().unwrap_or(Type::Bool);
                    out.push((format!("held_{}", c_ident(l)), ty));
                }
            }
        }
        out
    }

    /// C condition for "this chain is active this cycle".
    fn chain_cond(&self, ck: &ol_ir::Clock, scope: &Scope) -> String {
        let parts: Vec<String> = ck
            .conditions()
            .iter()
            .map(|(var, on)| {
                let r = scope.ref_var(var);
                if *on {
                    r
                } else {
                    format!("!{r}")
                }
            })
            .collect();
        if parts.is_empty() {
            "true".to_string()
        } else {
            parts.join(" && ")
        }
    }
}

#[derive(Debug)]
struct Scope {
    inputs: BTreeSet<String>,
    outputs: BTreeSet<String>,
    locals: BTreeSet<String>,
    is_stateful: bool,
}

impl Scope {
    fn ref_var(&self, name: &str) -> String {
        if self.inputs.contains(name) {
            format!("in->{}", c_ident(name))
        } else if self.outputs.contains(name) {
            format!("out->{}", c_ident(name))
        } else if self.locals.contains(name) {
            c_ident(name)
        } else {
            // Constants and enum variants are emitted under their own names.
            name.to_string()
        }
    }
}

struct EmitCtx<'a> {
    scope: &'a Scope,
    project: &'a Project,
    call_sites: &'a HashMap<usize, CallSite>,
    clocks: &'a NodeClocks,
    /// Declared type of every name in scope — lets the iterator emitter
    /// recover an array operand's length for the `for` bound.
    types: &'a HashMap<String, Type>,
    /// Disambiguates the temporaries of multiple iterators in one node.
    iter_seq: usize,
}

fn emit_equation_body(eq: &Equation, ctx: &mut EmitCtx, out: &mut String) {
    // Array iterators are always the whole RHS (typecheck enforces it) and
    // emit as a `for` loop rather than an expression.
    if let Expr::Iterate { kind, node, init, arrays } = &eq.rhs {
        emit_iterator(&eq.lhs[0], *kind, node, init.as_deref(), arrays, ctx, out);
        return;
    }

    // C has no whole-array assignment, so an array-literal RHS (an array MAKE or
    // SLICE block, or an inline `[…]`) is written element by element.
    if eq.lhs.len() == 1 {
        if let Expr::Array { items } = &eq.rhs {
            let lhs = ctx.scope.ref_var(&eq.lhs[0]);
            for (i, item) in items.iter().enumerate() {
                let (stmts, e) = lower_anf(item, ctx);
                for s in stmts {
                    out.push_str(&s);
                }
                let _ = writeln!(out, "  {lhs}[{i}] = {e};");
            }
            return;
        }
    }

    // Multi-output: only direct top-level Call binding is supported.
    if eq.lhs.len() > 1 {
        if let Expr::Call { args, .. } = &eq.rhs {
            let key = &eq.rhs as *const Expr as usize;
            let site = ctx
                .call_sites
                .get(&key)
                .expect("multi-output call missing site index");
            let callee = ctx
                .project
                .find_node(&site.callee_name)
                .expect("callee resolved");
            let (stmts, arg_strs) = lower_args(args, ctx);
            for s in stmts {
                out.push_str(&s);
            }
            emit_call_block(callee, site.idx, &arg_strs, out);
            for (lhs, p) in eq.lhs.iter().zip(callee.outputs.iter()) {
                let l = ctx.scope.ref_var(lhs);
                let _ = writeln!(out, "  {l} = __out{}.{};", site.idx, c_ident(&p.name));
            }
        } else {
            let _ = writeln!(out, "  /* unsupported multi-output rhs */");
        }
        return;
    }

    let (stmts, rhs_expr) = lower_anf(&eq.rhs, ctx);
    for s in stmts {
        out.push_str(&s);
    }
    let lhs = ctx.scope.ref_var(&eq.lhs[0]);
    let _ = writeln!(out, "  {lhs} = {rhs_expr};");
}

/// Emit an array iterator as a `for` loop. The iterated `F` is a stateless
/// function, so each step is a plain `F_step(&in, &out)` — no state pointer.
/// `map` writes the result array element by element; `fold` threads an
/// accumulator and assigns the scalar result once.
fn emit_iterator(
    lhs: &str,
    kind: ol_ir::IterKind,
    f_name: &str,
    init: Option<&Expr>,
    arrays: &[Expr],
    ctx: &mut EmitCtx,
    out: &mut String,
) {
    let seq = ctx.iter_seq;
    ctx.iter_seq += 1;
    let callee = match ctx.project.find_node(f_name) {
        Some(c) => c,
        None => {
            let _ = writeln!(out, "  /* iterator over unknown `{f_name}` */");
            return;
        }
    };
    // Loop bound from the first array operand's declared length.
    let n = arrays.first().and_then(|a| array_len_of(a, ctx)).unwrap_or(0);
    let i = format!("__it{seq}i");
    let inp = format!("__it{seq}in");
    let outp = format!("__it{seq}out");

    if matches!(kind, ol_ir::IterKind::Fold) {
        // acc = seed; for k { in.acc=acc; in.elem=a[k]; F_step; acc=out; } lhs=acc;
        let acc = format!("__it{seq}acc");
        let (stmts, seed) = init
            .map(|e| lower_anf(e, ctx))
            .unwrap_or_else(|| (vec![], "0".into()));
        for s in stmts {
            out.push_str(&s);
        }
        let acc_ty = callee.outputs.first().map(|p| p.ty.c_name()).unwrap_or_else(|| "int32_t".into());
        let _ = writeln!(out, "  {acc_ty} {acc} = {seed};");
        let arr = lower_operand(&arrays[0], ctx);
        let _ = writeln!(out, "  for (int {i} = 0; {i} < {n}; {i}++) {{");
        let _ = writeln!(out, "    {f_name}_Input {inp};");
        let _ = writeln!(out, "    {f_name}_Output {outp};");
        if let Some(p) = callee.inputs.first() {
            let _ = writeln!(out, "    {inp}.{} = {acc};", c_ident(&p.name));
        }
        if let Some(p) = callee.inputs.get(1) {
            let _ = writeln!(out, "    {inp}.{} = {arr}[{i}];", c_ident(&p.name));
        }
        let _ = writeln!(out, "    {f_name}_step(&{inp}, &{outp});");
        if let Some(p) = callee.outputs.first() {
            let _ = writeln!(out, "    {acc} = {outp}.{};", c_ident(&p.name));
        }
        let _ = writeln!(out, "  }}");
        let _ = writeln!(out, "  {} = {acc};", ctx.scope.ref_var(lhs));
        return;
    }

    // map: for k { in.<inj>=aj[k]; F_step; lhs[k]=out.<o>; }
    let arr_refs: Vec<String> = arrays.iter().map(|a| lower_operand(a, ctx)).collect();
    let lhs_ref = ctx.scope.ref_var(lhs);
    let _ = writeln!(out, "  for (int {i} = 0; {i} < {n}; {i}++) {{");
    let _ = writeln!(out, "    {f_name}_Input {inp};");
    let _ = writeln!(out, "    {f_name}_Output {outp};");
    for (p, a) in callee.inputs.iter().zip(arr_refs.iter()) {
        let _ = writeln!(out, "    {inp}.{} = {a}[{i}];", c_ident(&p.name));
    }
    let _ = writeln!(out, "    {f_name}_step(&{inp}, &{outp});");
    if let Some(p) = callee.outputs.first() {
        let _ = writeln!(out, "    {lhs_ref}[{i}] = {outp}.{};", c_ident(&p.name));
    }
    let _ = writeln!(out, "  }}");
}

/// C reference to an array operand. A bare variable resolves through the
/// scope; richer array expressions (a record field, a 2-D index) lower to an
/// indexable lvalue. The result is something `[__i]` can be appended to.
fn lower_operand(expr: &Expr, ctx: &mut EmitCtx) -> String {
    match expr {
        Expr::Var { name } => ctx.scope.ref_var(name),
        other => {
            let (stmts, e) = lower_anf(other, ctx);
            // Array operands never need preceding statements in practice
            // (they are lvalues), but keep any that arise.
            debug_assert!(stmts.is_empty(), "array operand produced statements");
            e
        }
    }
}

/// The static length of an array-typed operand, for the loop bound.
fn array_len_of(expr: &Expr, ctx: &EmitCtx) -> Option<u32> {
    match expr {
        Expr::Var { name } => match ctx.types.get(name) {
            Some(Type::Array { len, .. }) => Some(*len),
            _ => None,
        },
        Expr::Field { base, field } => {
            let bt = expr_type(base, ctx)?;
            if let Type::Named { name } = bt {
                let fields = record_fields(&name, ctx.project)?;
                if let Some(Type::Array { len, .. }) =
                    fields.iter().find(|f| &f.name == field).map(|f| &f.ty)
                {
                    return Some(*len);
                }
            }
            None
        }
        _ => None,
    }
}

/// Best-effort static type of an expression — enough for [`array_len_of`] to
/// resolve record-of-array operands and for the fixed-point cast/multiply
/// emitter to recover an operand's Q-format. Returns `None` when the type
/// cannot be determined locally (the caller then emits the plain form).
fn expr_type(expr: &Expr, ctx: &EmitCtx) -> Option<Type> {
    match expr {
        Expr::Const { lit } => Some(match lit {
            Literal::Bool { .. } => Type::Bool,
            Literal::Int { .. } => Type::Int64,
            Literal::Float { .. } => Type::Float64,
            Literal::Char { .. } => Type::Char,
        }),
        Expr::Var { name } => ctx.types.get(name).cloned().or_else(|| {
            ctx.project
                .packages
                .iter()
                .flat_map(|p| p.constants.iter())
                .find(|c| &c.name == name)
                .map(|c| c.ty.clone())
        }),
        Expr::Field { base, field } => {
            if let Some(Type::Named { name }) = expr_type(base, ctx) {
                let fields = record_fields(&name, ctx.project)?;
                return fields.iter().find(|f| &f.name == field).map(|f| f.ty.clone());
            }
            None
        }
        Expr::Index { base, .. } => match expr_type(base, ctx)? {
            Type::Array { elem, .. } => Some(*elem),
            _ => None,
        },
        Expr::Cast { to, .. } => Some(to.clone()),
        Expr::Unary { op, arg } => match op {
            UnaryOp::Not => Some(Type::Bool),
            UnaryOp::Neg => expr_type(arg, ctx),
        },
        Expr::Binary { op, lhs, .. } => match op {
            BinOp::And | BinOp::Or | BinOp::Xor | BinOp::Implies | BinOp::Eq | BinOp::Neq
            | BinOp::Lt | BinOp::Le | BinOp::Gt | BinOp::Ge => Some(Type::Bool),
            // Arithmetic / bitwise take the (matching) operand type.
            _ => expr_type(lhs, ctx),
        },
        Expr::Pre { arg } => expr_type(arg, ctx),
        Expr::Arrow { body, .. } => expr_type(body, ctx),
        Expr::IfThenElse { then_branch, .. } => expr_type(then_branch, ctx),
        Expr::When { arg, .. } => expr_type(arg, ctx),
        Expr::Merge { on_true, .. } => expr_type(on_true, ctx),
        Expr::Intrinsic { .. } => Some(Type::Float64),
        Expr::Call { node, .. } => ctx
            .project
            .all_nodes()
            .find(|n| &n.name == node)
            .filter(|n| n.outputs.len() == 1)
            .map(|n| n.outputs[0].ty.clone()),
        _ => None,
    }
}

/// C expression for a `numeric_cast`, honoring fixed-point scaling so the
/// generated code matches the IR simulator cell-for-cell. `src` is the operand's
/// best-effort static type (`None` ⇒ treat an into-fixed source as integer).
fn emit_cast_expr(to: &Type, src: Option<&Type>, a: &str) -> String {
    match (to, src) {
        // Into fixed: rescale the source into the backing integer.
        (Type::Fixed { frac, .. }, src) => {
            let store = to.c_name();
            match src {
                Some(Type::Fixed { frac: from, .. }) if from > frac => {
                    format!("(({store})(((int64_t)({a})) >> {}))", from - frac)
                }
                Some(Type::Fixed { frac: from, .. }) => {
                    format!("(({store})(((int64_t)({a})) << {}))", frac - from)
                }
                Some(t) if t.is_float() => {
                    format!("(({store})round((double)({a}) * (double)(1LL << {frac})))")
                }
                _ => format!("(({store})(((int64_t)({a})) << {frac}))"),
            }
        }
        // Out of fixed: exact divide to float, truncate-toward-zero to integer.
        (t, Some(Type::Fixed { frac, .. })) if t.is_float() => {
            format!("(({})((double)({a}) / (double)(1LL << {frac})))", t.c_name())
        }
        (t, Some(Type::Fixed { frac, .. })) if t.is_integer() => {
            format!("(({})(((int64_t)({a})) / ((int64_t)1 << {frac})))", t.c_name())
        }
        // Plain numeric cast.
        _ => format!("(({}){a})", to.c_name()),
    }
}

fn record_fields<'a>(name: &str, project: &'a Project) -> Option<&'a Vec<ol_ir::RecordField>> {
    for pkg in &project.packages {
        for t in &pkg.types {
            if let TypeBody::Record { name: rn, fields } = &t.body {
                if rn == name {
                    return Some(fields);
                }
            }
        }
    }
    None
}

fn lower_args(args: &[Expr], ctx: &mut EmitCtx) -> (Vec<String>, Vec<String>) {
    let mut all_stmts = Vec::new();
    let mut arg_strs = Vec::new();
    for a in args {
        let (s, e) = lower_anf(a, ctx);
        all_stmts.extend(s);
        arg_strs.push(e);
    }
    (all_stmts, arg_strs)
}

fn emit_call_block(callee: &NodeDef, idx: usize, arg_strs: &[String], out: &mut String) {
    let name = &callee.name;
    let _ = writeln!(out, "  {name}_Input __in{idx};");
    let _ = writeln!(out, "  {name}_Output __out{idx};");
    for (p, a) in callee.inputs.iter().zip(arg_strs.iter()) {
        let _ = writeln!(out, "  __in{idx}.{} = {};", c_ident(&p.name), a);
    }
    if callee.is_function() {
        let _ = writeln!(out, "  {name}_step(&__in{idx}, &__out{idx});");
    } else {
        let _ = writeln!(out, "  {name}_step(&self->sub_{idx}, &__in{idx}, &__out{idx});");
    }
}

/// Lower `expr` into (preceding statements, substituted expression). Calls are
/// hoisted into named struct pairs (`__inN` / `__outN`) and substituted with
/// `__outN.<output_name>` in the surrounding expression.
fn lower_anf(expr: &Expr, ctx: &mut EmitCtx) -> (Vec<String>, String) {
    match expr {
        Expr::Const { lit } => {
            let s = match lit {
                Literal::Bool { value } => if *value { "true" } else { "false" }.into(),
                Literal::Int { value } => format!("({value})"),
                Literal::Float { value } => format!("({value})"),
                Literal::Char { value } => format!("({value})"),
            };
            (vec![], s)
        }
        Expr::Var { name } => (vec![], ctx.scope.ref_var(name)),
        Expr::Cast { to, arg } => {
            let src = expr_type(arg, ctx);
            let (s, a) = lower_anf(arg, ctx);
            (s, emit_cast_expr(to, src.as_ref(), &a))
        }
        Expr::Intrinsic { func, args } => {
            // float64-only intrinsics map to the double <math.h> functions.
            let mut stmts = Vec::new();
            let mut parts = Vec::with_capacity(args.len());
            for a in args {
                let (s, e) = lower_anf(a, ctx);
                stmts.extend(s);
                parts.push(e);
            }
            (stmts, format!("{}({})", func.c_name(false), parts.join(", ")))
        }
        Expr::Unary { op, arg } => {
            let (s, a) = lower_anf(arg, ctx);
            let r = match op {
                UnaryOp::Not => format!("(!{a})"),
                UnaryOp::Neg => format!("(-{a})"),
            };
            (s, r)
        }
        Expr::Binary { op, lhs, rhs } => {
            let (mut s, l) = lower_anf(lhs, ctx);
            let (sr, r) = lower_anf(rhs, ctx);
            s.extend(sr);
            // Fixed-point multiply/divide use an i64 intermediate, narrowed by
            // the storage cast — identical to the simulator's stored-value ops.
            // Multiply shifts the product right by frac; divide shifts the
            // numerator left by frac first. (Add/sub/compare are plain integer
            // ops on the stored value.)
            if matches!(op, BinOp::Mul | BinOp::Div) {
                if let Some(Type::Fixed { signed, bits, frac }) = expr_type(lhs, ctx) {
                    let store = Type::Fixed { signed, bits, frac }.c_name();
                    let expr = if *op == BinOp::Mul {
                        format!("(({store})(((int64_t)({l}) * (int64_t)({r})) >> {frac}))")
                    } else {
                        format!("(({store})((((int64_t)({l})) << {frac}) / (int64_t)({r})))")
                    };
                    return (s, expr);
                }
            }
            let sym = match op {
                BinOp::And => "&&",
                BinOp::Or => "||",
                BinOp::Xor => "^",
                BinOp::Implies => return (s, format!("((!{l}) || ({r}))")),
                BinOp::Eq => "==",
                BinOp::Neq => "!=",
                BinOp::Lt => "<",
                BinOp::Le => "<=",
                BinOp::Gt => ">",
                BinOp::Ge => ">=",
                BinOp::Add => "+",
                BinOp::Sub => "-",
                BinOp::Mul => "*",
                BinOp::Div => "/",
                BinOp::Mod => "%",
                BinOp::BitAnd => "&",
                BinOp::BitOr => "|",
                BinOp::BitXor => "^",
                BinOp::Shl => "<<",
                BinOp::Shr => ">>",
            };
            (s, format!("({l} {sym} {r})"))
        }
        Expr::IfThenElse {
            cond,
            then_branch,
            else_branch,
        } => {
            let (mut s, c) = lower_anf(cond, ctx);
            let (st, t) = lower_anf(then_branch, ctx);
            let (se, e) = lower_anf(else_branch, ctx);
            s.extend(st);
            s.extend(se);
            (s, format!("({c} ? {t} : {e})"))
        }
        Expr::Pre { arg } => {
            if let Expr::Var { name } = arg.as_ref() {
                (vec![], format!("self->{}", state_field_name(name)))
            } else {
                (vec![], format!("/* pre of complex expr unsupported: {arg:?} */ 0"))
            }
        }
        Expr::Arrow { init, body } => {
            let (mut s, i) = lower_anf(init, ctx);
            let (sb, b) = lower_anf(body, ctx);
            s.extend(sb);
            // A clocked arrow counts ticks of ITS clock: init on the chain's
            // first active cycle, body afterwards. Base-clocked arrows keep
            // the node-wide initialized flag (same thing for the base chain).
            let key = expr as *const Expr as usize;
            let first = match ctx.clocks.info.site_clocks.get(&key) {
                Some(ck) if !ck.is_base() => {
                    format!("!self->{}", ctx.clocks.chain_fields[&ck.key()])
                }
                _ if ctx.scope.is_stateful => "!self->initialized".to_string(),
                _ => "!false".to_string(),
            };
            (s, format!("({first} ? ({i}) : ({b}))"))
        }
        Expr::Call { args, .. } => {
            let key = expr as *const Expr as usize;
            let site = ctx
                .call_sites
                .get(&key)
                .expect("call site index not registered");
            let callee = ctx
                .project
                .find_node(&site.callee_name)
                .expect("callee resolves");

            let (mut s, arg_strs) = lower_args(args, ctx);
            let mut block = String::new();
            emit_call_block(callee, site.idx, &arg_strs, &mut block);
            s.push(block);

            if callee.outputs.len() == 1 {
                (s, format!("__out{}.{}", site.idx, callee.outputs[0].name))
            } else {
                // Non-top-level multi-output call — return only the first
                // output; the surrounding equation should have used a tuple
                // binding. Emit a comment so it's visible in the generated C.
                (
                    s,
                    format!(
                        "/* multi-output call used in expression position */ __out{}.{}",
                        site.idx, callee.outputs[0].name
                    ),
                )
            }
        }
        Expr::Field { base, field } => {
            let (s, b) = lower_anf(base, ctx);
            (s, format!("{b}.{field}"))
        }
        Expr::Index { base, index } => {
            let (mut s, b) = lower_anf(base, ctx);
            let (si, i) = lower_anf(index, ctx);
            s.extend(si);
            (s, format!("{b}[{i}]"))
        }
        Expr::Tuple { .. } => (vec![], "/* tuple */ 0".into()),
        // Composite literals in expression position are not directly C-assignable
        // (C has no whole-array assignment); the supported path is a named
        // `static const` referenced as an lvalue, then indexed / field-accessed.
        Expr::Array { .. } => (vec![], "/* array literal */ 0".into()),
        // A record literal is a C compound literal — assignable to a struct
        // lvalue, so a struct MAKE block emits `out = (T){ .f = v, … };`.
        Expr::Struct { ty, fields } => {
            let mut stmts = Vec::new();
            let parts: Vec<String> = fields
                .iter()
                .map(|fi| {
                    let (s, v) = lower_anf(&fi.value, ctx);
                    stmts.extend(s);
                    format!(".{} = {}", fi.field, v)
                })
                .collect();
            (stmts, format!("({}){{ {} }}", ty, parts.join(", ")))
        }
        // Iterators are emitted at the equation level (a `for` loop), never
        // as a sub-expression — typecheck guarantees they are the whole RHS.
        Expr::Iterate { .. } => (vec![], "/* iterator is not an expression */ 0".into()),
        // Sampling is pure evaluation here: the equation guard (or the merge
        // ternary) already decides which cycles reach this expression.
        Expr::When { arg, .. } => lower_anf(arg, ctx),
        Expr::Merge { clock, on_true, on_false } => {
            let (mut s, t) = lower_anf(on_true, ctx);
            let (sf, f) = lower_anf(on_false, ctx);
            s.extend(sf);
            let c = ctx.scope.ref_var(clock);
            (s, format!("({c} ? ({t}) : ({f}))"))
        }
    }
}

/// Emit a complete C declarator (`<type> <name>`, with array brackets after the
/// name as C requires). Caller appends `;` or `= ...` etc.
fn type_decl(ty: &Type, name: &str) -> String {
    match ty {
        Type::Array { elem, len } => format!("{} {name}[{len}]", elem.c_name()),
        other => format!("{} {name}", other.c_name()),
    }
}

fn state_field_name(name: &str) -> String {
    format!("prev_{name}")
}

/// C identifier for a model variable. Model names are only constrained to be
/// identifiers, so `unsigned`, `for`, or `double` are all legal — and would
/// break the generated code. Keywords (and the generated parameter names
/// `in`/`out`/`self`) get a trailing underscore; CSV headers, traces, and
/// diagnostics keep the model's own names.
pub(crate) fn c_ident(name: &str) -> String {
    const RESERVED: &[&str] = &[
        // C11 keywords.
        "auto", "break", "case", "char", "const", "continue", "default", "do",
        "double", "else", "enum", "extern", "float", "for", "goto", "if",
        "inline", "int", "long", "register", "restrict", "return", "short",
        "signed", "sizeof", "static", "struct", "switch", "typedef", "union",
        "unsigned", "void", "volatile", "while",
        // stdbool/stdint names the generated code relies on.
        "bool", "true", "false",
        // Parameter names of every generated _step/_init function.
        "in", "out", "self",
    ];
    if RESERVED.contains(&name) {
        format!("{name}_")
    } else {
        name.to_string()
    }
}

fn state_driver_name(state_field: &str, scope: &Scope) -> String {
    if let Some(stripped) = state_field.strip_prefix("prev_") {
        // The "previous value" for a `pre x` is the current cycle's `x` after
        // the step body runs. Resolve where that name lives so the driver is
        // valid C — inputs come from `in->`, outputs from `out->`, and locals
        // are plain identifiers.
        scope.ref_var(stripped)
    } else {
        state_field.to_string()
    }
}

/// Walk a node and collect every `pre x` so we know what state fields to add.
fn node_state_fields(node: &NodeDef) -> Vec<(String, Type)> {
    let mut fields = Vec::new();
    let mut seen = BTreeSet::new();
    let env: std::collections::HashMap<&str, &Type> = node
        .inputs
        .iter()
        .map(|p| (p.name.as_str(), &p.ty))
        .chain(node.outputs.iter().map(|p| (p.name.as_str(), &p.ty)))
        .chain(node.locals.iter().map(|l| (l.name.as_str(), &l.ty)))
        .collect();

    for eq in &node.equations {
        collect_pre_vars(&eq.rhs, &env, &mut fields, &mut seen);
    }
    fields
}

fn collect_pre_vars(
    expr: &Expr,
    env: &std::collections::HashMap<&str, &Type>,
    out: &mut Vec<(String, Type)>,
    seen: &mut BTreeSet<String>,
) {
    match expr {
        Expr::Pre { arg } => {
            if let Expr::Var { name } = arg.as_ref() {
                if seen.insert(name.clone()) {
                    let ty = env
                        .get(name.as_str())
                        .copied()
                        .cloned()
                        .unwrap_or(Type::Bool);
                    out.push((state_field_name(name), ty));
                }
            } else {
                collect_pre_vars(arg, env, out, seen);
            }
        }
        Expr::Unary { arg, .. } | Expr::Cast { arg, .. } => collect_pre_vars(arg, env, out, seen),
        Expr::Binary { lhs, rhs, .. } => {
            collect_pre_vars(lhs, env, out, seen);
            collect_pre_vars(rhs, env, out, seen);
        }
        Expr::IfThenElse {
            cond,
            then_branch,
            else_branch,
        } => {
            collect_pre_vars(cond, env, out, seen);
            collect_pre_vars(then_branch, env, out, seen);
            collect_pre_vars(else_branch, env, out, seen);
        }
        Expr::Arrow { init, body } => {
            collect_pre_vars(init, env, out, seen);
            collect_pre_vars(body, env, out, seen);
        }
        Expr::Call { args, .. } => {
            for a in args {
                collect_pre_vars(a, env, out, seen);
            }
        }
        Expr::Field { base, .. } => collect_pre_vars(base, env, out, seen),
        Expr::Index { base, index } => {
            collect_pre_vars(base, env, out, seen);
            collect_pre_vars(index, env, out, seen);
        }
        Expr::Tuple { items } | Expr::Array { items } => {
            for i in items {
                collect_pre_vars(i, env, out, seen);
            }
        }
        Expr::Struct { fields, .. } => {
            for fi in fields {
                collect_pre_vars(&fi.value, env, out, seen);
            }
        }
        Expr::When { arg, .. } => collect_pre_vars(arg, env, out, seen),
        Expr::Merge { on_true, on_false, .. } => {
            collect_pre_vars(on_true, env, out, seen);
            collect_pre_vars(on_false, env, out, seen);
        }
        Expr::Iterate { init, arrays, .. } => {
            if let Some(i) = init {
                collect_pre_vars(i, env, out, seen);
            }
            for a in arrays {
                collect_pre_vars(a, env, out, seen);
            }
        }
        Expr::Intrinsic { args, .. } => {
            for a in args {
                collect_pre_vars(a, env, out, seen);
            }
        }
        Expr::Const { .. } | Expr::Var { .. } => {}
    }
}
