//! Contract monitor generation (Phase 5).
//!
//! Each contract produces a C monitor that, given the same input/output
//! structs the production code uses, asserts assumptions and guarantees and
//! tracks the currently active mode. The monitor lives in its own translation
//! unit so production C-Lite stays clean.

use std::fmt::Write as _;

use ol_contract_ir::{parse_contracts, ContractDef};
use ol_ir::{BinOp, Expr, Literal, Project, UnaryOp};

#[derive(Debug, Clone)]
pub struct MonitorBundle {
    pub header: String,
    pub source: String,
}

pub fn emit_monitors(project: &Project) -> MonitorBundle {
    let mut header = String::new();
    let mut source = String::new();

    let _ = writeln!(header, "/* Generated by OpenLustre Studio (contract monitors). */");
    let _ = writeln!(header, "#ifndef OL_GENERATED_MONITORS_H");
    let _ = writeln!(header, "#define OL_GENERATED_MONITORS_H");
    let _ = writeln!(header, "#include \"openlustre_generated.h\"");
    let _ = writeln!(header, "#include <stddef.h>");
    header.push('\n');

    let _ = writeln!(source, "/* Generated by OpenLustre Studio. */");
    let _ = writeln!(source, "#include \"openlustre_monitors.h\"");
    let _ = writeln!(source, "#include <stdio.h>");
    let _ = writeln!(source, "#include <string.h>");
    source.push('\n');
    // Small label-appending helper shared by every monitor in the file.
    let _ = writeln!(source, "static void _ol_append(char* buf, size_t buf_size, const char* sep, const char* s) {{");
    let _ = writeln!(source, "  if (!buf || buf_size == 0) return;");
    let _ = writeln!(source, "  size_t off = strlen(buf);");
    let _ = writeln!(source, "  if (off + 1 >= buf_size) return;");
    let _ = writeln!(source, "  if (off > 0) {{");
    let _ = writeln!(source, "    snprintf(buf + off, buf_size - off, \"%s\", sep);");
    let _ = writeln!(source, "    off = strlen(buf);");
    let _ = writeln!(source, "  }}");
    let _ = writeln!(source, "  if (off + 1 >= buf_size) return;");
    let _ = writeln!(source, "  snprintf(buf + off, buf_size - off, \"%s\", s);");
    let _ = writeln!(source, "}}");
    source.push('\n');

    for pkg in &project.packages {
        let (contracts, _) = parse_contracts(&pkg.contracts);
        for c in &contracts {
            // Find the node that uses this contract so we know which I/O
            // struct types to reference.
            let owner = pkg
                .nodes
                .iter()
                .find(|n| n.contract.as_deref() == Some(c.name.as_str()))
                .map(|n| n.name.clone())
                .unwrap_or_else(|| c.name.clone());
            emit_monitor(c, &owner, &mut header, &mut source);
            header.push('\n');
            source.push('\n');
        }
    }

    let _ = writeln!(header, "#endif /* OL_GENERATED_MONITORS_H */");
    MonitorBundle { header, source }
}

fn emit_monitor(c: &ContractDef, owner: &str, header: &mut String, source: &mut String) {
    let monitor_name = format!("{}_monitor", c.name);
    let _ = writeln!(header, "/* monitor for contract `{}` over `{owner}` */", c.name);
    let _ = writeln!(
        header,
        "typedef struct {{ int active_mode; bool any_violation; }} {monitor_name}_State;"
    );
    let _ = writeln!(header, "void {monitor_name}_reset({monitor_name}_State* s);");
    let _ = writeln!(
        header,
        "void {monitor_name}_check({monitor_name}_State* s, const {owner}_Input* in, const {owner}_Output* out, char* active_mode_buf, size_t active_mode_size, char* violations_buf, size_t violations_size);"
    );

    let _ = writeln!(source, "void {monitor_name}_reset({monitor_name}_State* s) {{");
    let _ = writeln!(source, "  s->active_mode = -1;");
    let _ = writeln!(source, "  s->any_violation = false;");
    let _ = writeln!(source, "}}");
    let _ = writeln!(
        source,
        "void {monitor_name}_check({monitor_name}_State* s, const {owner}_Input* in, const {owner}_Output* out, char* active_mode_buf, size_t active_mode_size, char* violations_buf, size_t violations_size) {{"
    );
    let _ = writeln!(source, "  if (active_mode_buf && active_mode_size > 0) active_mode_buf[0] = 0;");
    let _ = writeln!(source, "  if (violations_buf && violations_size > 0) violations_buf[0] = 0;");

    let scope = MonScope {
        inputs: c.inputs.iter().map(|p| p.name.clone()).collect(),
        outputs: c.outputs.iter().map(|p| p.name.clone()).collect(),
    };

    for (i, a) in c.assumptions.iter().enumerate() {
        let cond = emit_mon_expr(&a.expr, &scope);
        let label = a.name.clone().unwrap_or_else(|| format!("assumption#{i}"));
        let _ = writeln!(
            source,
            "  if (!({cond})) {{ s->any_violation = true; _ol_append(violations_buf, violations_size, \"|\", \"{label}\"); }}"
        );
    }
    for (i, g) in c.guarantees.iter().enumerate() {
        let cond = emit_mon_expr(&g.expr, &scope);
        let label = g.name.clone().unwrap_or_else(|| format!("guarantee#{i}"));
        let _ = writeln!(
            source,
            "  if (!({cond})) {{ s->any_violation = true; _ol_append(violations_buf, violations_size, \"|\", \"{label}\"); }}"
        );
    }
    for (idx, m) in c.modes.iter().enumerate() {
        let require_parts: Vec<String> = m
            .requires
            .iter()
            .map(|r| format!("({})", emit_mon_expr(r, &scope)))
            .collect();
        let require_cond = if require_parts.is_empty() {
            "true".to_string()
        } else {
            require_parts.join(" && ")
        };
        let _ = writeln!(source, "  if ({require_cond}) {{");
        let _ = writeln!(source, "    s->active_mode = {idx};");
        let _ = writeln!(
            source,
            "    _ol_append(active_mode_buf, active_mode_size, \"|\", \"{}\");",
            m.name
        );
        for (j, e) in m.ensures.iter().enumerate() {
            let cond = emit_mon_expr(e, &scope);
            let _ = writeln!(
                source,
                "    if (!({cond})) {{ s->any_violation = true; _ol_append(violations_buf, violations_size, \"|\", \"{}::ensure#{j}\"); }}",
                m.name
            );
        }
        let _ = writeln!(source, "  }}");
    }

    let _ = writeln!(source, "  if (active_mode_buf && active_mode_buf[0] == 0) snprintf(active_mode_buf, active_mode_size, \"%s\", \"<none>\");");
    let _ = writeln!(source, "  if (violations_buf && violations_buf[0] == 0) snprintf(violations_buf, violations_size, \"%s\", \"<none>\");");

    let _ = writeln!(source, "}}");
}

struct MonScope {
    inputs: Vec<String>,
    outputs: Vec<String>,
}

impl MonScope {
    fn ref_name(&self, name: &str) -> String {
        if self.inputs.iter().any(|n| n == name) {
            format!("in->{name}")
        } else if self.outputs.iter().any(|n| n == name) {
            format!("out->{name}")
        } else {
            name.to_string()
        }
    }
}

fn emit_mon_expr(expr: &Expr, scope: &MonScope) -> String {
    match expr {
        Expr::Const { lit: Literal::Bool { value } } => if *value { "true" } else { "false" }.into(),
        Expr::Const { lit: Literal::Int { value } } => format!("({value})"),
        Expr::Const { lit: Literal::Float { value } } => format!("({value})"),
        Expr::Var { name } => scope.ref_name(name),
        Expr::Unary { op, arg } => {
            let a = emit_mon_expr(arg, scope);
            match op {
                UnaryOp::Not => format!("(!{a})"),
                UnaryOp::Neg => format!("(-{a})"),
            }
        }
        Expr::Binary { op, lhs, rhs } => {
            let l = emit_mon_expr(lhs, scope);
            let r = emit_mon_expr(rhs, scope);
            let sym = match op {
                BinOp::And => "&&",
                BinOp::Or => "||",
                BinOp::Implies => {
                    return format!("((!{l}) || ({r}))");
                }
                BinOp::Xor => "^",
                BinOp::Eq => "==",
                BinOp::Neq => "!=",
                BinOp::Lt => "<",
                BinOp::Le => "<=",
                BinOp::Gt => ">",
                BinOp::Ge => ">=",
                BinOp::Add => "+",
                BinOp::Sub => "-",
                BinOp::Mul => "*",
                BinOp::Div => "/",
                BinOp::Mod => "%",
            };
            format!("({l} {sym} {r})")
        }
        Expr::IfThenElse {
            cond,
            then_branch,
            else_branch,
        } => format!(
            "({} ? {} : {})",
            emit_mon_expr(cond, scope),
            emit_mon_expr(then_branch, scope),
            emit_mon_expr(else_branch, scope)
        ),
        Expr::Pre { .. } | Expr::Arrow { .. } => "1 /* temporal in monitor: lowered to true */".into(),
        Expr::Call { node, .. } => format!("/* call {node} elided */ 1"),
        Expr::Field { base, field } => format!("{}.{field}", emit_mon_expr(base, scope)),
        Expr::Index { base, index } => format!(
            "{}[{}]",
            emit_mon_expr(base, scope),
            emit_mon_expr(index, scope)
        ),
        Expr::Tuple { .. } => "/* tuple */ 0".into(),
    }
}
