//! Contract monitor generation (Phase 5).
//!
//! Each contract produces a C monitor that, given the same input/output
//! structs the production code uses, asserts assumptions and guarantees and
//! tracks the currently active mode. The clauses themselves are computed by
//! the contract's observer node (`ContractDef::observer`), compiled here with
//! the ordinary node emitter, so temporal operators and ghost variables get
//! the model's semantics. The monitor lives in its own translation unit so
//! production C-Lite stays clean.

use std::fmt::Write as _;

use ol_contract_ir::{parse_contracts, ContractDef, ObserverSignal};
use ol_ir::Project;

#[derive(Debug, Clone)]
pub struct MonitorBundle {
    pub header: String,
    pub source: String,
}

pub fn emit_monitors(project: &Project) -> MonitorBundle {
    let mut header = String::new();
    let mut source = String::new();

    let _ = writeln!(header, "/* Generated by OpenLustre Studio (contract monitors). */");
    let _ = writeln!(header, "#ifndef OL_GENERATED_MONITORS_H");
    let _ = writeln!(header, "#define OL_GENERATED_MONITORS_H");
    let _ = writeln!(header, "#include \"openlustre_generated.h\"");
    let _ = writeln!(header, "#include <stddef.h>");
    header.push('\n');

    let _ = writeln!(source, "/* Generated by OpenLustre Studio. */");
    let _ = writeln!(source, "#include \"openlustre_monitors.h\"");
    let _ = writeln!(source, "#include <stdio.h>");
    let _ = writeln!(source, "#include <string.h>");
    source.push('\n');
    // Small label-appending helper shared by every monitor in the file.
    let _ = writeln!(source, "static void _ol_append(char* buf, size_t buf_size, const char* sep, const char* s) {{");
    let _ = writeln!(source, "  if (!buf || buf_size == 0) return;");
    let _ = writeln!(source, "  size_t off = strlen(buf);");
    let _ = writeln!(source, "  if (off + 1 >= buf_size) return;");
    let _ = writeln!(source, "  if (off > 0) {{");
    let _ = writeln!(source, "    snprintf(buf + off, buf_size - off, \"%s\", sep);");
    let _ = writeln!(source, "    off = strlen(buf);");
    let _ = writeln!(source, "  }}");
    let _ = writeln!(source, "  if (off + 1 >= buf_size) return;");
    let _ = writeln!(source, "  snprintf(buf + off, buf_size - off, \"%s\", s);");
    let _ = writeln!(source, "}}");
    source.push('\n');

    for pkg in &project.packages {
        let (contracts, _) = parse_contracts(&pkg.contracts);
        for c in &contracts {
            // Find the node that uses this contract so we know which I/O
            // struct types to reference.
            let owner = pkg
                .nodes
                .iter()
                .find(|n| n.contract.as_deref() == Some(c.name.as_str()))
                .map(|n| n.name.clone())
                .unwrap_or_else(|| c.name.clone());
            emit_monitor(c, &owner, project, &mut header, &mut source);
            header.push('\n');
            source.push('\n');
        }
    }

    let _ = writeln!(header, "#endif /* OL_GENERATED_MONITORS_H */");
    MonitorBundle { header, source }
}

fn emit_monitor(
    c: &ContractDef,
    owner: &str,
    project: &Project,
    header: &mut String,
    source: &mut String,
) {
    // The contract's observer is an ordinary operator: emit it with the same
    // code generator as the model, so `pre` / `->`, ghost variables and calls
    // in contract clauses compile with exactly the model's semantics (and
    // match the simulator, which steps the same node).
    let obs = c.observer();
    let on = obs.node.name.clone();
    crate::emit_node_header(&obs.node, project, header);
    crate::emit_node_source(&obs.node, project, source, &mut Vec::new());

    let monitor_name = format!("{}_monitor", c.name);
    let _ = writeln!(header, "/* monitor for contract `{}` over `{owner}` */", c.name);
    let _ = writeln!(
        header,
        "typedef struct {{ int active_mode; bool any_violation; {on}_State obs; }} {monitor_name}_State;"
    );
    let _ = writeln!(header, "void {monitor_name}_reset({monitor_name}_State* s);");
    let _ = writeln!(
        header,
        "void {monitor_name}_check({monitor_name}_State* s, const {owner}_Input* in, const {owner}_Output* out, char* active_mode_buf, size_t active_mode_size, char* violations_buf, size_t violations_size);"
    );

    let _ = writeln!(source, "void {monitor_name}_reset({monitor_name}_State* s) {{");
    let _ = writeln!(source, "  s->active_mode = -1;");
    let _ = writeln!(source, "  s->any_violation = false;");
    let _ = writeln!(source, "  {on}_init(&s->obs);");
    let _ = writeln!(source, "}}");
    let _ = writeln!(
        source,
        "void {monitor_name}_check({monitor_name}_State* s, const {owner}_Input* in, const {owner}_Output* out, char* active_mode_buf, size_t active_mode_size, char* violations_buf, size_t violations_size) {{"
    );
    let _ = writeln!(source, "  if (active_mode_buf && active_mode_size > 0) active_mode_buf[0] = 0;");
    let _ = writeln!(source, "  if (violations_buf && violations_size > 0) violations_buf[0] = 0;");

    // Feed the observer this cycle's inputs and outputs (memcpy: array fields
    // can't be assigned in C), then step it.
    let _ = writeln!(source, "  {on}_Input oi;");
    let _ = writeln!(source, "  {on}_Output oo;");
    let _ = writeln!(source, "  memset(&oi, 0, sizeof(oi));");
    for (p, from) in c.inputs.iter().map(|p| (p, "in")).chain(c.outputs.iter().map(|p| (p, "out"))) {
        let f = crate::c_ident(&p.name);
        let _ = writeln!(source, "  memcpy(&oi.{f}, &{from}->{f}, sizeof(oi.{f}));");
    }
    let _ = writeln!(source, "  {on}_step(&s->obs, &oi, &oo);");

    // Interpret its signals exactly as `Observer::verdict` does: assumptions,
    // guarantees, then each mode (active when all its requires hold).
    let field = |i: usize| format!("oo.{}", crate::c_ident(&obs.node.outputs[i].name));
    for (i, sig) in obs.signals.iter().enumerate() {
        match sig {
            ObserverSignal::Assumption { label, .. } | ObserverSignal::Guarantee { label, .. } => {
                let _ = writeln!(
                    source,
                    "  if (!{}) {{ s->any_violation = true; _ol_append(violations_buf, violations_size, \"|\", \"{label}\"); }}",
                    field(i)
                );
            }
            _ => {}
        }
    }
    for (m, mode) in c.modes.iter().enumerate() {
        let requires: Vec<String> = obs
            .signals
            .iter()
            .enumerate()
            .filter(|(_, s)| matches!(s, ObserverSignal::Require { mode, .. } if *mode == m))
            .map(|(i, _)| field(i))
            .collect();
        let cond = if requires.is_empty() { "true".to_string() } else { requires.join(" && ") };
        let _ = writeln!(source, "  if ({cond}) {{");
        let _ = writeln!(source, "    s->active_mode = {m};");
        let _ = writeln!(
            source,
            "    _ol_append(active_mode_buf, active_mode_size, \"|\", \"{}\");",
            mode.name
        );
        for (i, sig) in obs.signals.iter().enumerate() {
            if let ObserverSignal::Ensure { mode: em, index } = sig {
                if *em == m {
                    let _ = writeln!(
                        source,
                        "    if (!{}) {{ s->any_violation = true; _ol_append(violations_buf, violations_size, \"|\", \"{}::ensure#{index}\"); }}",
                        field(i),
                        mode.name
                    );
                }
            }
        }
        let _ = writeln!(source, "  }}");
    }
    let _ = writeln!(source, "  (void)oo;");

    let _ = writeln!(source, "  if (active_mode_buf && active_mode_buf[0] == 0) snprintf(active_mode_buf, active_mode_size, \"%s\", \"<none>\");");
    let _ = writeln!(source, "  if (violations_buf && violations_buf[0] == 0) snprintf(violations_buf, violations_size, \"%s\", \"<none>\");");

    let _ = writeln!(source, "}}");
}
