//! OpenLustre Studio: Lustre emitter (Phase 4 target A — modern Kind 2).
//!
//! Produces a single `.lus` text file that round-trips through Kind 2. The
//! emitter is purely syntactic — by the time we reach this stage the IR has
//! been verified by `ol_typecheck` and `ol_contract_check`. The contract
//! emitter in `ol_cocospec_emit` calls `format_expr` here to keep contract
//! syntax aligned with node-body syntax.

use std::fmt::Write as _;

use ol_ir::{BinOp, Expr, Literal, NodeDef, NodeKind, Package, Project, TypeBody, UnaryOp};

pub fn emit_project(project: &Project) -> String {
    let mut out = String::new();
    let _ = writeln!(out, "-- Generated by OpenLustre Studio.");
    let _ = writeln!(out, "-- project: {}", project.name);
    out.push('\n');
    for pkg in &project.packages {
        emit_package(pkg, &mut out);
    }
    if let Some(main) = &project.main {
        let _ = writeln!(out, "--%MAIN ; entry: {main}");
    }
    out
}

pub fn emit_package(pkg: &Package, out: &mut String) {
    if !pkg.types.is_empty() {
        let _ = writeln!(out, "-- package: {} (types)", pkg.name);
        for t in &pkg.types {
            emit_type(t, out);
        }
        out.push('\n');
    }
    if !pkg.constants.is_empty() {
        let _ = writeln!(out, "-- package: {} (constants)", pkg.name);
        for c in &pkg.constants {
            let _ = writeln!(
                out,
                "const {} : {} = {};",
                c.name,
                c.ty.lustre_name(),
                format_expr_lustre(&c.value)
            );
        }
        out.push('\n');
    }
    for n in &pkg.nodes {
        emit_node(n, out);
        out.push('\n');
    }
}

fn emit_type(t: &ol_ir::TypeDef, out: &mut String) {
    match &t.body {
        TypeBody::Enum(e) => {
            let _ = writeln!(out, "type {} = enum {{ {} }};", e.name, e.variants.join(", "));
        }
        TypeBody::Record { name, fields } => {
            let body = fields
                .iter()
                .map(|f| format!("{}: {}", f.name, f.ty.lustre_name()))
                .collect::<Vec<_>>()
                .join("; ");
            let _ = writeln!(out, "type {name} = struct {{ {body} }};");
        }
        TypeBody::Alias { name, target } => {
            let _ = writeln!(out, "type {name} = {};", target.lustre_name());
        }
    }
}

pub fn emit_node(node: &NodeDef, out: &mut String) {
    let kind = match node.kind {
        NodeKind::Function => "function",
        NodeKind::Operator => "node",
        NodeKind::Imported => "function imported",
    };

    let inputs = node
        .inputs
        .iter()
        .map(|p| format!("{}: {}", p.name, p.ty.lustre_name()))
        .collect::<Vec<_>>()
        .join("; ");
    let outputs = node
        .outputs
        .iter()
        .map(|p| format!("{}: {}", p.name, p.ty.lustre_name()))
        .collect::<Vec<_>>()
        .join("; ");

    let _ = writeln!(out, "{kind} {}({inputs}) returns ({outputs});", node.name);

    if node.is_imported() {
        let _ = writeln!(out, "-- body is provided by external C (see manifest).");
        return;
    }

    if !node.locals.is_empty() {
        let locals = node
            .locals
            .iter()
            .map(|l| format!("{}: {}", l.name, l.ty.lustre_name()))
            .collect::<Vec<_>>()
            .join("; ");
        let _ = writeln!(out, "var {locals};");
    }
    let _ = writeln!(out, "let");
    for eq in &node.equations {
        let lhs = if eq.lhs.len() == 1 {
            eq.lhs[0].clone()
        } else {
            format!("({})", eq.lhs.join(", "))
        };
        let _ = writeln!(out, "  {lhs} = {};", format_expr_lustre(&eq.rhs));
    }
    let _ = writeln!(out, "tel");
}

/// Surface formatter: round-trips through `ol_stdlib::parse_expr`, so the
/// GUI can show and re-parse equations (casts print as `int16(x)`).
pub fn format_expr(expr: &Expr) -> String {
    format_expr_prec(expr, 0, false)
}

/// Kind 2 formatter: identical except for constructs standard Lustre lacks.
/// Casts emit as `int_cast(...)` / `real_cast(...)` function calls — the
/// same convention as `bit_and`/`bit_or` — so a user can supply matching
/// Lustre functions when proving models that convert between families.
/// (Integer widths are already collapsed to unbounded `int` in this view.)
pub fn format_expr_lustre(expr: &Expr) -> String {
    format_expr_prec(expr, 0, true)
}

fn format_expr_prec(expr: &Expr, parent_prec: u8, lustre: bool) -> String {
    let (text, prec) = match expr {
        // A char prints as `'a'` in our surface syntax (and round-trips through
        // the parser), but as its integer byte in Lustre, which has no char.
        Expr::Const { lit: Literal::Char { value } } if lustre => (value.to_string(), 100),
        Expr::Const { lit } => (format_literal(lit), 100),
        Expr::Var { name } => (name.clone(), 100),
        Expr::Unary { op, arg } => {
            let inner = format_expr_prec(arg, 90, lustre);
            let t = match op {
                UnaryOp::Not => format!("not {inner}"),
                UnaryOp::Neg => format!("- {inner}"),
            };
            (t, 90)
        }
        Expr::Binary { op, lhs, rhs } => {
            // Bit operators are not part of standard Lustre. We emit them as
            // function calls (`bit_and`, `bit_or`, ...) so a user can supply
            // matching imported Lustre functions for Kind 2.
            if let Some(fname) = bit_op_name(*op) {
                let l = format_expr_prec(lhs, 0, lustre);
                let r = format_expr_prec(rhs, 0, lustre);
                (format!("{fname}({l}, {r})"), 100)
            } else {
                let (sym, prec) = bin_op_syntax(*op);
                let l = format_expr_prec(lhs, prec, lustre);
                let r = format_expr_prec(rhs, prec + 1, lustre);
                (format!("{l} {sym} {r}"), prec)
            }
        }
        Expr::IfThenElse {
            cond,
            then_branch,
            else_branch,
        } => {
            let c = format_expr_prec(cond, 0, lustre);
            let t = format_expr_prec(then_branch, 0, lustre);
            let e = format_expr_prec(else_branch, 0, lustre);
            (format!("if {c} then {t} else {e}"), 5)
        }
        Expr::Pre { arg } => (format!("pre {}", format_expr_prec(arg, 80, lustre)), 80),
        Expr::Arrow { init, body } => {
            let i = format_expr_prec(init, 15, lustre);
            let b = format_expr_prec(body, 14, lustre);
            (format!("{i} -> {b}"), 15)
        }
        Expr::Call { node, args } => {
            let parts = args
                .iter()
                .map(|a| format_expr_prec(a, 0, lustre))
                .collect::<Vec<_>>()
                .join(", ");
            (format!("{node}({parts})"), 100)
        }
        Expr::Field { base, field } => {
            (format!("{}.{field}", format_expr_prec(base, 100, lustre)), 100)
        }
        Expr::Index { base, index } => (
            format!(
                "{}[{}]",
                format_expr_prec(base, 100, lustre),
                format_expr_prec(index, 0, lustre)
            ),
            100,
        ),
        Expr::Tuple { items } => {
            let parts = items
                .iter()
                .map(|i| format_expr_prec(i, 0, lustre))
                .collect::<Vec<_>>()
                .join(", ");
            (format!("({parts})"), 100)
        }
        // Array literal: `[a, b]` for Lustre, `[a; b]` for our surface (which
        // is what the parser reads back).
        Expr::Array { items } => {
            let sep = if lustre { ", " } else { "; " };
            let parts = items
                .iter()
                .map(|i| format_expr_prec(i, 0, lustre))
                .collect::<Vec<_>>()
                .join(sep);
            (format!("[{parts}]"), 100)
        }
        // Record literal: `T { f = v; … }` for Lustre, `T { f: v, … }` for our
        // surface syntax.
        Expr::Struct { ty, fields } => {
            let parts = fields
                .iter()
                .map(|fi| {
                    let v = format_expr_prec(&fi.value, 0, lustre);
                    if lustre {
                        format!("{} = {v}", fi.field)
                    } else {
                        format!("{}: {v}", fi.field)
                    }
                })
                .collect::<Vec<_>>()
                .join(if lustre { "; " } else { ", " });
            (format!("{ty} {{ {parts} }}"), 100)
        }
        Expr::Cast { to, arg } => {
            let a = format_expr_prec(arg, 0, lustre);
            let t = if lustre {
                let f = if to.is_float() { "real_cast" } else { "int_cast" };
                format!("{f}({a})")
            } else if let ol_ir::Type::Fixed { signed, bits, frac } = to {
                // Surface syntax round-trips through the parser's fixed names.
                format!("{}fix{bits}_{frac}({a})", if *signed { "s" } else { "u" })
            } else {
                format!("{}({a})", cast_type_name(to))
            };
            (t, 100)
        }
        // `when` sits between `->` (15) and `=>` (18); left-associative so
        // nested sampling prints as `x when c when d`.
        Expr::When { arg, clock, on } => {
            let a = format_expr_prec(arg, 16, lustre);
            let t = if *on {
                format!("{a} when {clock}")
            } else {
                format!("{a} when not {clock}")
            };
            (t, 16)
        }
        Expr::Merge { clock, on_true, on_false } => {
            let t = format_expr_prec(on_true, 0, lustre);
            let f = format_expr_prec(on_false, 0, lustre);
            let s = if lustre {
                // Lustre V6 / Kind 2 boolean merge-case syntax.
                format!("merge {clock} (true -> {t}) (false -> {f})")
            } else {
                format!("merge({clock}, {t}, {f})")
            };
            (s, 100)
        }
        // Array iterators print function-style and round-trip through the
        // parser. The Kind 2 view uses the same text — iterator bodies are
        // not yet lowered for proving (roadmap, like the bit-op convention).
        Expr::Iterate { kind, node, init, arrays } => {
            let name = match kind {
                ol_ir::IterKind::Map => "map",
                ol_ir::IterKind::Fold => "fold",
            };
            let mut parts: Vec<String> = vec![node.clone()];
            if let Some(i) = init {
                parts.push(format_expr_prec(i, 0, lustre));
            }
            parts.extend(arrays.iter().map(|a| format_expr_prec(a, 0, lustre)));
            (format!("{name}({})", parts.join(", ")), 100)
        }
        // Float intrinsics print function-style and round-trip through the
        // parser. The Kind 2 view uses the same call text — the user supplies
        // matching Lustre functions to prove models that use them, as with the
        // cast / bit-op convention.
        Expr::Intrinsic { func, args } => {
            let parts: Vec<String> =
                args.iter().map(|a| format_expr_prec(a, 0, lustre)).collect();
            (format!("{}({})", func.name(), parts.join(", ")), 100)
        }
    };
    if prec < parent_prec {
        format!("({text})")
    } else {
        text
    }
}

/// The surface token for a cast target — exactly what `parse_type` accepts,
/// so a formatted cast parses back to the same IR.
fn cast_type_name(t: &ol_ir::Type) -> &'static str {
    use ol_ir::Type::*;
    match t {
        Int8 => "int8",
        Int16 => "int16",
        Int32 => "int32",
        Int64 => "int64",
        Uint8 => "uint8",
        Uint16 => "uint16",
        Uint32 => "uint32",
        Uint64 => "uint64",
        Float32 => "float32",
        Float64 => "float64",
        // Non-numeric targets are rejected by the typechecker; this arm only
        // affects how an already-invalid model is displayed.
        _ => "int32",
    }
}

fn bin_op_syntax(op: BinOp) -> (&'static str, u8) {
    match op {
        BinOp::Or => ("or", 20),
        BinOp::Xor => ("xor", 20),
        BinOp::And => ("and", 25),
        BinOp::Implies => ("=>", 18),
        BinOp::Eq => ("=", 30),
        BinOp::Neq => ("<>", 30),
        BinOp::Lt => ("<", 30),
        BinOp::Le => ("<=", 30),
        BinOp::Gt => (">", 30),
        BinOp::Ge => (">=", 30),
        BinOp::Add => ("+", 40),
        BinOp::Sub => ("-", 40),
        BinOp::Mul => ("*", 50),
        BinOp::Div => ("/", 50),
        BinOp::Mod => ("mod", 50),
        // Bit ops never reach here — they are rendered as function calls.
        BinOp::BitAnd | BinOp::BitOr | BinOp::BitXor | BinOp::Shl | BinOp::Shr => ("?bit?", 0),
    }
}

fn bit_op_name(op: BinOp) -> Option<&'static str> {
    Some(match op {
        BinOp::BitAnd => "bit_and",
        BinOp::BitOr => "bit_or",
        BinOp::BitXor => "bit_xor",
        BinOp::Shl => "shift_left",
        BinOp::Shr => "shift_right",
        _ => return None,
    })
}

fn format_literal(lit: &Literal) -> String {
    match lit {
        Literal::Bool { value } => value.to_string(),
        Literal::Int { value } => value.to_string(),
        Literal::Float { value: f } => {
            let s = format!("{f}");
            if s.contains('.') {
                s
            } else {
                format!("{s}.0")
            }
        }
        Literal::Char { value } => format_char_literal(*value),
    }
}

/// Render a char byte as a quoted surface literal (`'a'`, `'\n'`, …) that the
/// parser reads back to the same byte.
fn format_char_literal(b: u8) -> String {
    match b {
        b'\n' => "'\\n'".into(),
        b'\t' => "'\\t'".into(),
        b'\r' => "'\\r'".into(),
        0 => "'\\0'".into(),
        b'\'' => "'\\''".into(),
        b'\\' => "'\\\\'".into(),
        _ => format!("'{}'", b as char),
    }
}
