//! OpenLustre Studio: Lustre emitter (Phase 4 target A — modern Kind 2).
//!
//! Produces a single `.lus` text file that round-trips through Kind 2. The
//! emitter is purely syntactic — by the time we reach this stage the IR has
//! been verified by `ol_typecheck` and `ol_contract_check`. The contract
//! emitter in `ol_cocospec_emit` calls `format_expr` here to keep contract
//! syntax aligned with node-body syntax.

use std::fmt::Write as _;

use ol_ir::{BinOp, Expr, Literal, NodeDef, NodeKind, Package, Project, TypeBody, UnaryOp};

pub fn emit_project(project: &Project) -> String {
    let mut out = String::new();
    let _ = writeln!(out, "-- Generated by OpenLustre Studio.");
    let _ = writeln!(out, "-- project: {}", project.name);
    out.push('\n');
    for pkg in &project.packages {
        emit_package(pkg, &mut out);
    }
    if let Some(main) = &project.main {
        let _ = writeln!(out, "--%MAIN ; entry: {main}");
    }
    out
}

pub fn emit_package(pkg: &Package, out: &mut String) {
    if !pkg.types.is_empty() {
        let _ = writeln!(out, "-- package: {} (types)", pkg.name);
        for t in &pkg.types {
            emit_type(t, out);
        }
        out.push('\n');
    }
    for n in &pkg.nodes {
        emit_node(n, out);
        out.push('\n');
    }
}

fn emit_type(t: &ol_ir::TypeDef, out: &mut String) {
    match &t.body {
        TypeBody::Enum(e) => {
            let _ = writeln!(out, "type {} = enum {{ {} }};", e.name, e.variants.join(", "));
        }
        TypeBody::Record { name, fields } => {
            let body = fields
                .iter()
                .map(|f| format!("{}: {}", f.name, f.ty.lustre_name()))
                .collect::<Vec<_>>()
                .join("; ");
            let _ = writeln!(out, "type {name} = struct {{ {body} }};");
        }
        TypeBody::Alias { name, target } => {
            let _ = writeln!(out, "type {name} = {};", target.lustre_name());
        }
    }
}

pub fn emit_node(node: &NodeDef, out: &mut String) {
    let kind = match node.kind {
        NodeKind::Function => "function",
        NodeKind::Operator => "node",
        NodeKind::Imported => "function imported",
    };

    let inputs = node
        .inputs
        .iter()
        .map(|p| format!("{}: {}", p.name, p.ty.lustre_name()))
        .collect::<Vec<_>>()
        .join("; ");
    let outputs = node
        .outputs
        .iter()
        .map(|p| format!("{}: {}", p.name, p.ty.lustre_name()))
        .collect::<Vec<_>>()
        .join("; ");

    let _ = writeln!(out, "{kind} {}({inputs}) returns ({outputs});", node.name);

    if node.is_imported() {
        let _ = writeln!(out, "-- body is provided by external C (see manifest).");
        return;
    }

    if !node.locals.is_empty() {
        let locals = node
            .locals
            .iter()
            .map(|l| format!("{}: {}", l.name, l.ty.lustre_name()))
            .collect::<Vec<_>>()
            .join("; ");
        let _ = writeln!(out, "var {locals};");
    }
    let _ = writeln!(out, "let");
    for eq in &node.equations {
        let lhs = if eq.lhs.len() == 1 {
            eq.lhs[0].clone()
        } else {
            format!("({})", eq.lhs.join(", "))
        };
        let _ = writeln!(out, "  {lhs} = {};", format_expr(&eq.rhs));
    }
    let _ = writeln!(out, "tel");
}

pub fn format_expr(expr: &Expr) -> String {
    format_expr_prec(expr, 0)
}

fn format_expr_prec(expr: &Expr, parent_prec: u8) -> String {
    let (text, prec) = match expr {
        Expr::Const { lit } => (format_literal(lit), 100),
        Expr::Var { name } => (name.clone(), 100),
        Expr::Unary { op, arg } => {
            let inner = format_expr_prec(arg, 90);
            let t = match op {
                UnaryOp::Not => format!("not {inner}"),
                UnaryOp::Neg => format!("- {inner}"),
            };
            (t, 90)
        }
        Expr::Binary { op, lhs, rhs } => {
            let (sym, prec) = bin_op_syntax(*op);
            let l = format_expr_prec(lhs, prec);
            let r = format_expr_prec(rhs, prec + 1);
            (format!("{l} {sym} {r}"), prec)
        }
        Expr::IfThenElse {
            cond,
            then_branch,
            else_branch,
        } => {
            let c = format_expr_prec(cond, 0);
            let t = format_expr_prec(then_branch, 0);
            let e = format_expr_prec(else_branch, 0);
            (format!("if {c} then {t} else {e}"), 5)
        }
        Expr::Pre { arg } => (format!("pre {}", format_expr_prec(arg, 80)), 80),
        Expr::Arrow { init, body } => {
            let i = format_expr_prec(init, 15);
            let b = format_expr_prec(body, 14);
            (format!("{i} -> {b}"), 15)
        }
        Expr::Call { node, args } => {
            let parts = args
                .iter()
                .map(|a| format_expr_prec(a, 0))
                .collect::<Vec<_>>()
                .join(", ");
            (format!("{node}({parts})"), 100)
        }
        Expr::Field { base, field } => {
            (format!("{}.{field}", format_expr_prec(base, 100)), 100)
        }
        Expr::Index { base, index } => (
            format!("{}[{}]", format_expr_prec(base, 100), format_expr_prec(index, 0)),
            100,
        ),
        Expr::Tuple { items } => {
            let parts = items
                .iter()
                .map(|i| format_expr_prec(i, 0))
                .collect::<Vec<_>>()
                .join(", ");
            (format!("({parts})"), 100)
        }
    };
    if prec < parent_prec {
        format!("({text})")
    } else {
        text
    }
}

fn bin_op_syntax(op: BinOp) -> (&'static str, u8) {
    match op {
        BinOp::Or => ("or", 20),
        BinOp::Xor => ("xor", 20),
        BinOp::And => ("and", 25),
        BinOp::Implies => ("=>", 18),
        BinOp::Eq => ("=", 30),
        BinOp::Neq => ("<>", 30),
        BinOp::Lt => ("<", 30),
        BinOp::Le => ("<=", 30),
        BinOp::Gt => (">", 30),
        BinOp::Ge => (">=", 30),
        BinOp::Add => ("+", 40),
        BinOp::Sub => ("-", 40),
        BinOp::Mul => ("*", 50),
        BinOp::Div => ("/", 50),
        BinOp::Mod => ("mod", 50),
    }
}

fn format_literal(lit: &Literal) -> String {
    match lit {
        Literal::Bool { value } => value.to_string(),
        Literal::Int { value } => value.to_string(),
        Literal::Float { value: f } => {
            let s = format!("{f}");
            if s.contains('.') {
                s
            } else {
                format!("{s}.0")
            }
        }
    }
}
